ProjetP1: clem.c File Reference
clem.c File Reference
#include "clem.h"
#include "etienne.h"
#include "gabin.h"
#include "paul.h"
#include "structure.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
Functions
arbreChemins creerArbreChemins (arbreChemins a, int positionL, int positionC, int **maze, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe.
arbreChemins creerArbreCheminsCache (arbreChemins a, int positionL, int positionC, int **maze, arbreChemins a_parent, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe avec son parent et ses fils.
void afficherArbreChemins (arbreChemins a, int **maze)
Permet d'afficher chaque case contenus dans l'arbre des chemins.
int deplacementValide (int positionL, int positionC, arbreChemins *a, Joueur j, int **maze, int taille)
Permet de valider si un déplacement est possible ou non.
void ajouterItemInventaire (Jeu *jeu, int type, char *name)
Ajoute un objet dans l'inventaire du joueur.
void healthPotionEvent (Jeu *jeu)
Permet de réaliser un évenement qui soigne le joueur.
void medikitEvent (Jeu *jeu)
Permet de réaliser un évenement qui soigne le joueur.
void damageTrapEvent (Jeu *jeu)
Permet d'effectuer l'évenement de dégats sur le joueur.
void milkPotionEvent (Jeu *jeu)
Permet d'effectuer l'évenement verre de lait (supprime les effets négatifs du joueur)
void verifEvent (Jeu *jeu, int ***maze, int positionL, int positionC)
Vérifie si un event est placé sur la case demandé par le joueur et effectue un évenement aléatoirement.
char * emoji (int type)
Permet d'afficher les émojis selon l'item rencontré ou utilisé
void afficherUseItem (int type)
Permet d'afficher un objet rencontré ou utilisé dans le labyrinthe.
void verifPoisonFeu (Joueur *j)
Permet d'effectuer les évenements poison et feu en influant sur la vie du joueur.
void verifEtatEvent (Joueur *j, int *typeEvent)
Vérifie l'état de l'évenement pour l'affichage et la fin du poison et du feu.
void eventJoueur (int *typeEvent, Joueur *j)
Effectue l'event en vérifiant son type et l'état du joueur (souvent le poison ou le feu)
int lenInt (int score)
Calcule la longueur d'un entier.
void scorePrint (int scoreLen)
Permet d'espacer correctement seulement la taille du score du joueur
void afficherScore (int level, int score)
Affiche le score et le niveau du joueur.
void afficherInventaire (Jeu jeu)
Permet d'afficher l'inventaire du joueur et sa vie.
void useItem (Jeu *jeu, int typeInput)
Permet d'utiliser un item dans son inventaire.
void modeHealth (int *pvHealth, int typeMode)
void initJeu (Jeu *jeu)
Permet d'initialiser le jeu.
void jouerMaze (Jeu *jeu)
Permet de lancer la partie avec les options sélectionées et de jouer.
void mazePlacementSimple (int ***maze, int taille, Joueur *j)
void setCheck (int ***maze, int taille, int randPlacement)
void mazePlacementComplexe (int ***maze, int taille, Joueur *j, int posMazeL, int posMazeC)
void creerMegaMaze (Jeu *jeu)
Crée un labyrinthe 3x3 avec des checkpoints et des clefs.
void creerMaze (Jeu *jeu)
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
void placerEvents (Maze *maze, int level)
Permet de placer les events de manières aléatoire dans le labyrythne.
void placerKeys (Maze *maze, Joueur *j)
Place les clefs dans les labyrinthes 3x3.
void findCheck (Jeu *jeu, int positionInverse, int mode)
void verifCheck (Jeu *jeu, int **maze, int positionL, int positionC)
void deplacementMaze (Jeu *jeu, arbreChemins *a, int ***maze, int positions[2])
Permet de vérifier et effectuer les bonnes fonctions selon les actions du joueur.
void playMazeSimple (Jeu *jeu)
Permet de jouer avec le labyrinthe.
void playMegaMaze (Jeu *jeu)
Permet de jouer avec les labyrinthes 3x3.
void jouerJeu (Jeu *jeu)
Permet de lancher la partie avec un jeu initialisé
void gameOver (int level, int score, int highScore)
Affiche la fin de partie et sauvegarde le highscore dans un CSV.
void getScoreCSV (Jeu *jeu)
Récupère dans le CSV le highscore le plus haut du joueur.
void saveHighScoreCSV (int highScore, int score)
Enregistre dans le CSV le highscore le plus haut du joueur.
void initOptions (char ****optionsTab, Options *options)
Permet d'initialiser et d'allouer les options et les tableaux du menu options
void saveOptions (Options *options, int numOptions, int numId)
Permet de sauvegarder l'option selon la ligne et la valeur numId(choix du joueur pour une option)
int getOptions (Options *options, int numOptions)
Récupère à chaque selon la ligne la valeur de l'option afin d'afficher la dernière selectionée.
void optionChange (Options *options, char ***optionsTab)
void freeGame (Jeu *jeu)
Permet de libérer la mémoire.
void naviguerArbreChemins (arbreChemins a, Maze maze, int ***tabAriane, int *x)
(Algo A*) Permet naviguer dans l'arbre et d'incrémenter la valeur x à chaque case et de placer la valeur maximal sur la fin
void findEnd (int **tabAriane, int *lEnd, int *cEnd, int taille)
Permet de trouver la sortie du tabArianne.
void findEndArbre (int lEnd, int cEnd, arbreChemins aDebut, arbreChemins *aEnd)
Permet de trouver la sortie dans l'arbre des chemins.
void remonterArbre (arbreChemins a, int **tabAriane, Jeu *jeu)
Permet de trouver le chemins le plus court (algo A*), en prenant toujours la plus petite valeur aux alentours.
void filAriane2 (Jeu *jeu)
Permet d'afficher le fil d'Ariane.
Function Documentation
afficherArbreChemins()
afficherArbreChemins (arbreChemins a, int ** maze)
Permet d'afficher chaque case contenus dans l'arbre des chemins.
Author
Paul Brechenmacher
Date
(January 2nd, 2024 10:21 PM)
Parameters
[in] a Arbre des chemins
[in] maze Tableau 2D représentant le labyrinth
Definition at line 86 of file clem.c.
{
     printf("[%d - %d] --> %d\n",a->positions[0],a->positions[1],a->type);
     for(int n = 0; n < a->nbFils; n++){
         afficherArbreChemins(a->fils[n],maze);
     }
 }
References node::fils, node::nbFils, node::positions, and node::type.
afficherInventaire()
afficherInventaire (Jeu jeu)
Permet d'afficher l'inventaire du joueur et sa vie.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'inventaire du joueur et sa vie
Definition at line 336 of file clem.c.
{
 printf("\e[1;97m");
 printf("╔═1═╦═2═╦═3═╦═4═╦═5═╗\n");
 printf("║%s║%s║%s║%s║%s║  %d❤️\n",emoji(jeu.j.inventaire[0].type),emoji(jeu.j.inventaire[1].type),emoji(jeu.j.inventaire[2].type),emoji(jeu.j.inventaire[3].type),emoji(jeu.j.inventaire[4].type),jeu.j.pvHealth);
 printf("╚═══╩═══╩═══╩═══╩═══╝\n");
 printf(reset);
 }
References emoji(), Joueur::inventaire, Jeu::j, Joueur::pvHealth, reset, and Item::type.
Referenced by jouerMaze().
afficherScore()
afficherScore (int score, int level)
Affiche le score et le niveau du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] score Score du joueur
[in] level Niveau du joueur
Definition at line 323 of file clem.c.
{
 printf("\e[1;97m");
 printf("╔══════════════╗    ╔══════════════╗\n");
 if(lenInt((level/2)+1)==2){
     printf("║  ""\e[1;92m""Niveau %d""\e[1;97m""   ║    ║  ""\e[1;33m""%d 🪙""\e[1;97m",(level/2)+1,score);
 }else{
     printf("║   ""\e[1;92m""Niveau %d""\e[1;97m""   ║    ║  ""\e[1;33m""%d 🪙""\e[1;97m",(level/2)+1,score);
 }
 scorePrint(lenInt(score));
 printf("╚══════════════╝    ╚══════════════╝\n");
 printf(reset);
 }
References lenInt(), reset, and scorePrint().
Referenced by gameOver(), and jouerMaze().
afficherUseItem()
afficherUseItem (int type)
Permet d'afficher un objet rencontré ou utilisé dans le labyrinthe.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] type Type d'objet utilisé ou rencontré dans le labyrinthe
Definition at line 263 of file clem.c.
{
     printf("╔═══════════════════════╗\n");
     printf("║ Vous avez utilisé %s ║\n",emoji(type));
     printf("╚═══════════════════════╝\n");
 }
References emoji().
Referenced by verifEtatEvent(), and verifPoisonFeu().
ajouterItemInventaire()
ajouterItemInventaire (Jeu * jeu, int type, char * name)
Ajoute un objet dans l'inventaire du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'inventaire
[in] type Type de l'objet à ajouter
[in] name Nom de l'objet à ajouter
[out] jeu Jeu contenant l'inventaire avec le nouvel item
Definition at line 120 of file clem.c.
{
     int nbItems = 0;
     while(jeu->j.inventaire[nbItems].type != NONE){
         nbItems++;
     }
     jeu->j.inventaire[nbItems].type = type;
     jeu->j.inventaire[nbItems].name = name;
 }
References Joueur::inventaire, Jeu::j, Item::name, NONE, and Item::type.
Referenced by healthPotionEvent(), medikitEvent(), and milkPotionEvent().
creerArbreChemins()
creerArbreChemins (arbreChemins a, int positionL, int positionC, int ** maze, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] positionL Position de la ligne de la case dans le labyrinthe à rajouter dans l'arbre
[in] positionC Position de la colonne de la case dans le labyrinthe à rajouter dans l'arbre
[in] a Arbre avec les chemins possibles
[in] maze Tableau contentant le labyrinthe
[in] taille Taille du labyrinthe
Returns
Arbre avec une nouvelle case accessible dans le labyrinthe
Definition at line 13 of file clem.c.
{
     arbreChemins a_parent;
     a_parent = malloc(sizeof(node));
     a_parent->nbFils = 1;
     a_parent->positions[0] = positionL;
     a_parent->positions[1] = positionC;
     return creerArbreCheminsCache(a,positionL,positionC,maze,a_parent,taille);
 }
References creerArbreCheminsCache(), node::nbFils, and node::positions.
Referenced by creerMaze(), playMegaMaze(), and verifCheck().
creerArbreCheminsCache()
creerArbreCheminsCache (arbreChemins a, int positionL, int positionC, int ** maze, arbreChemins a_parent, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe avec son parent et ses fils.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] positionL Position de la ligne de la case dans le labyrinthe à rajouter dans l'arbre
[in] positionC Position de la colonne de la case dans le labyrinthe à rajouter dans l'arbre
[in] a Arbre avec les chemins possibles
[in] maze Tableau contentant le labyrinthe
[in] a_parent Arbre parent permettant au joueur de revenir sur ses pas
[in] taille Taille du labyrinthe
Returns
Arbre avec une nouvelle case accessible dans le labyrinthe
Definition at line 23 of file clem.c.
{
         a = malloc(sizeof(node));
         a->fils = malloc(1 * sizeof(node*));
         a->positions[0] = positionL;
         a->positions[1] = positionC;
         a->parent = a_parent;
         a->nbFils = 0;
         //afficherMatrice(maze, SIZE);
         if(maze[a->positions[0]][a->positions[1]] == END){
             a->type = 0;
         }else{
             if(maze[a->positions[0]][a->positions[1]] == CHECKPOINT){
                 a->type = 2;
             }else{
                 a->type = 1;
             }
         }
         if(positionC != taille-1){
             if(maze[a->positions[0]][a->positions[1]+1] >= SPACE && (a->positions[0] != a->parent->positions[0] || a->positions[1]+1 != a->parent->positions[1])){ //DROITE
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL, positionC+1,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
             }
         }
         if(positionL != taille-1){
             if(maze[a->positions[0]+1][a->positions[1]] >= SPACE && (a->positions[0]+1 != a->parent->positions[0] || a->positions[1] != a->parent->positions[1])){ // BAS
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL+1, positionC,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
             }
         }
         if(positionL != 0){
             if(maze[a->positions[0]-1][a->positions[1]] >= SPACE && (a->positions[0]-1 != a->parent->positions[0] || a->positions[1] != a->parent->positions[1])){ //HAUT
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL-1, positionC,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
             }
         }
         if(positionC != 0){
             if(maze[a->positions[0]][a->positions[1]-1] >= SPACE && (a->positions[0] != a->parent->positions[0] || a->positions[1]-1 != a->parent->positions[1])){ //GAUCHE
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL, positionC-1,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
                 return a;
             }
             return a;
         }
         return a;
     }
References CHECKPOINT, END, node::fils, node::nbFils, node::parent, node::positions, SPACE, and node::type.
Referenced by creerArbreChemins().
creerMaze()
creerMaze (Jeu * jeu)
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'intégralité des variables du jeu
[out] jeu Jeu contenant le labyrinthe et l'arbre des chemins
Definition at line 550 of file clem.c.
{
     jeu->maze.sizeMaze = jeu->maze.sizeMaze + jeu->level;
     mazeGenerator(&jeu->maze.tabMaze,jeu->maze.sizeMaze);
     mazePlacementSimple(&jeu->maze.tabMaze,jeu->maze.sizeMaze,&jeu->j);
     jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
     if(jeu->maze.typeMaze){
         jeu->maze.arbreCheminDepart = jeu->maze.arbreChemin;
         }
 }
References Maze::arbreChemin, Maze::arbreCheminDepart, creerArbreChemins(), Jeu::j, Jeu::level, Jeu::maze, mazeGenerator(), mazePlacementSimple(), Joueur::positions, Maze::sizeMaze, Maze::tabMaze, and Maze::typeMaze.
Referenced by playMazeSimple().
creerMegaMaze()
creerMegaMaze (Jeu * jeu)
Crée un labyrinthe 3x3 avec des checkpoints et des clefs.
Author
Paul Brechenmacher
Date
(January 7th, 2024 2:11 PM)
Parameters
[in] jeu Jeu sans megaMaze(labyrinthe 3x3)
[out] jeu Jeu contenant un megaMaze avec des checkpoints et des clefs
Definition at line 531 of file clem.c.
{
     jeu->maze.sizeMaze = INITIALSIZE+(jeu->level);
     jeu->posMaze[0] = 1;
     jeu->posMaze[1] = 0;
     int size = 3;
     jeu->megamaze = (Maze**)malloc(size * sizeof(Maze*));
     for (int ligne = 0; ligne <  size; ligne++) {
         jeu->megamaze[ligne] = (Maze*)malloc(size * sizeof(Maze));
         for (int colonne= 0; colonne < size; colonne++) {
             mazeGenerator(&jeu->maze.tabMaze,jeu->maze.sizeMaze);
             mazePlacementComplexe(&jeu->maze.tabMaze,jeu->maze.sizeMaze,&jeu->j,ligne,colonne);
             jeu->maze.typeMaze = 0;
             jeu->megamaze[ligne][colonne] = jeu->maze;  // Initialiser la matrice avec des murs (-1)
         }
     }
 }
References INITIALSIZE, Jeu::j, Jeu::level, Jeu::maze, mazeGenerator(), mazePlacementComplexe(), Jeu::megamaze, Jeu::posMaze, Maze::sizeMaze, Maze::tabMaze, and Maze::typeMaze.
Referenced by playMegaMaze().
damageTrapEvent()
damageTrapEvent (Jeu * jeu)
Permet d'effectuer l'évenement de dégats sur le joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant la vie du joueur
[out] jeu Jeu contenant la vie du joueur modifiée
Definition at line 151 of file clem.c.
{
     jeu->j.pvHealth--;
 }
References Jeu::j, and Joueur::pvHealth.
Referenced by verifEvent().
deplacementMaze()
void deplacementMaze (Jeu * jeu, arbreChemins * a, int *** maze, int positions[2])
Permet de vérifier et effectuer les bonnes fonctions selon les actions du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant toutes la position et le labyrinthe avec les actions du joueurs
[in] a Arbre contenant les cases accessibles pour le joueur
[in] maze Pointeur du tableau 2D représentant le labyrinthe
[in] positions Tableau des positions du joueur
[out] jeu Jeu contenant toutes la position et le labyrinthe mis à jour
Definition at line 644 of file clem.c.
{
     switch (deplacementTouche(jeu->j.etatSobreJoueur)) {
                 case HAUT:
                     if(deplacementValide(positions[0]-1,positions[1],a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0]-1,positions[1]);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0]-1,positions[1]);
                             (*maze)[positions[0]-1][positions[1]] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[0]--;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case DROITE:
                     if(deplacementValide(positions[0],positions[1]+1,a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0],positions[1]+1);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0],positions[1]+1);
                             (*maze)[positions[0]][positions[1]+1] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[1]++;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case GAUCHE:
                     if(deplacementValide(positions[0],positions[1]-1,a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0],positions[1]-1);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0],positions[1]-1);
                             (*maze)[positions[0]][positions[1]-1] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[1]--;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case BAS:
                     if(deplacementValide(positions[0]+1,positions[1],a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0]+1,positions[1]);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0]+1,positions[1]);
                             (*maze)[positions[0]+1][positions[1]] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[0]++;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case HOTBAR1:
                     useItem(jeu,0);
                     break;
                 case HOTBAR2:
                     useItem(jeu,1);
                     break;
                 case HOTBAR3:
                     useItem(jeu,2);
                     break;
                 case HOTBAR4:
                     useItem(jeu,3);
                     break;
                 case HOTBAR5:
                     useItem(jeu,4);
                     break;
                 default:
                 printf("Invalid direction\n");
                     break;
             }
 }
References BAS, CHECKPOINT, deplacementTouche(), deplacementValide(), DROITE, Joueur::etatCheckPoint, Joueur::etatSobreJoueur, GAUCHE, HAUT, HOTBAR1, HOTBAR2, HOTBAR3, HOTBAR4, HOTBAR5, Jeu::j, Jeu::maze, PLAYER, Joueur::positions, Maze::sizeMaze, SPACE, useItem(), verifCheck(), and verifEvent().
Referenced by jouerMaze().
deplacementValide()
deplacementValide (int positionL, int positionC, arbreChemins * a, Joueur j, int ** maze, int taille)
Permet de valider si un déplacement est possible ou non.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
[in] a Arbre contenant les cases accessibles pour le joueur
[in] j Jeu contenant la position du joueur
[in] maze Tableau 2D représentant le labyrinthe
[in] taille Taille du labyrinthe
Returns
0 si déplacement invalide / 1 si déplacement valide
Definition at line 94 of file clem.c.
{
     int val = 0;
     if(positionL > -1 && positionC > -1 && positionC < taille && positionL < taille){
         if(maze[positionL][positionC] == END){
             if(!j.findKeys){
                 return 0;
             }
         }
     }
     for(int n = 0; n < (*a)->nbFils; n++){
         if((*a)->fils[n]->positions[0] == positionL && (*a)->fils[n]->positions[1] == positionC){
             *a = (*a)->fils[n];
             val = 1;
         }
     }
     if((*a)->parent->positions[0] == positionL && (*a)->parent->positions[1] == positionC){
             *a = (*a)->parent;
             val =  1;
         }
     return val;
 }
References END, node::fils, Joueur::findKeys, and node::parent.
Referenced by deplacementMaze().
emoji()
emoji (int type)
Permet d'afficher les émojis selon l'item rencontré ou utilisé
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] type Type d'émoji selon l'énumération itemListe
Returns
Chaine de caractère représentant l'émoji correspondant à son type
Definition at line 234 of file clem.c.
                      {
     switch (type) {
         case NONE:
             return " - ";
         case HEALTH:
             return "💊 ";
         case MEDIKIT:
             return "🚑 ";
         case DAMAGE:
             return "🤕 ";
         case FIRE:
             return "🔥 ";
         case DRUNK:
             return "🍾 ";
         case MILK:
             return "🥛 ";
         case ARIANE:
             return "🧶 ";
         case POISON:
             return "🧪 ";
         case SCORE:
             return "🪙 ";
         case FUN:
             return "🎷 ";
         default:
             return "Error";
     }
 }
References ARIANE, DAMAGE, DRUNK, FIRE, FUN, HEALTH, MEDIKIT, MILK, NONE, POISON, and SCORE.
Referenced by afficherInventaire(), and afficherUseItem().
eventJoueur()
eventJoueur (int * typeEvent, Joueur * j)
Effectue l'event en vérifiant son type et l'état du joueur (souvent le poison ou le feu)
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] j Pointeur du Joueur contenant les caractéristiques et les états du joueur
[in] typeEvent Type de l'event à effectuer et à vérifier
[out] j Joueur modifié avec un nouvel état (souvent le poison ou le feu)
Definition at line 298 of file clem.c.
{
     verifEtatEvent(j,typeEvent);
     verifPoisonFeu(j);
 }
References verifEtatEvent(), and verifPoisonFeu().
Referenced by jouerMaze().
filAriane2()
filAriane2 (Jeu * jeu)
Permet d'afficher le fil d'Ariane.
Author
Paul Brechenmacher
Date
(January 9th, 2024 9:22 PM)
Precondition
Le labyrinthe doit être sans les checkpoints (typeMaze = 1)
Parameters
[in] jeu Jeu contenant le labyrinthe
[out] jeu Jeu contenant le labyrinthe avec le fil d'Ariane visible
Definition at line 1030 of file clem.c.
{
     int x = 6;
     int** tabAriane = NULL;
     int cEnd,lEnd;
     allouerTab2(&tabAriane,jeu->maze.sizeMaze);
     naviguerArbreChemins(jeu->maze.arbreCheminDepart,jeu->maze,&tabAriane,&x);
     findEnd(tabAriane,&lEnd,&cEnd,jeu->maze.sizeMaze);
     arbreChemins aEnd = malloc(sizeof(node*));
     findEndArbre(lEnd,cEnd,jeu->maze.arbreCheminDepart,&aEnd);
     remonterArbre(aEnd,tabAriane,jeu);
 }
References allouerTab2(), Maze::arbreCheminDepart, findEnd(), findEndArbre(), Jeu::maze, naviguerArbreChemins(), remonterArbre(), and Maze::sizeMaze.
Referenced by verifEvent().
findCheck()
void findCheck (Jeu * jeu, int positionInverse, int mode)
Definition at line 586 of file clem.c.
{
     int i = 1;
     // mode 1 --> recherche ligne sinon  0 --> recherche colonne
     afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
     if(mode){
         while(jeu->maze.tabMaze[i][positionInverse] != CHECKPOINT && i < jeu->maze.sizeMaze){
             i++;
         }
         jeu->j.positions[0] = i;
         jeu->j.positions[1] = positionInverse;
     }else{
         while(jeu->maze.tabMaze[positionInverse][i] != CHECKPOINT && i < jeu->maze.sizeMaze){
             i++;
         }
         jeu->j.positions[0] = positionInverse;
         jeu->j.positions[1] = i;
     }
 }
References afficherMatrice1(), CHECKPOINT, Jeu::j, Jeu::maze, Jeu::options, Joueur::positions, Maze::sizeMaze, Maze::tabMaze, Options::typeEmoji, and Options::typeMode.
Referenced by verifCheck().
findEnd()
findEnd (int ** tabAriane, int * lEnd, int * cEnd, int taille)
Permet de trouver la sortie du tabArianne.
Author
Paul Brechenmacher
Date
(January 12th, 2024 6:37 PM)
Parameters
[in] tabAriane Tableau avec des valeurs de x incrementés sur les chemins
[in] lEnd Ligne d'arrivée non trouvée
[in] cEnd Colonne d'arrivée non trouvée
[in] taille Taille labyrinthe
[out] lEnd Ligne d'arrivée trouvée
[out] cEnd Colonne d'arrivée trouvée
Definition at line 976 of file clem.c.
{
   for(int i = 0; i < taille; i++) {
     for (int j = 0; j < taille; j++) {
       if(tabAriane[i][j] == taille*taille){
         *lEnd = i;
         *cEnd = j;
       }
      }
   }
 }
Referenced by filAriane2().
findEndArbre()
findEndArbre (int lEnd, int cEnd, arbreChemins aDebut, arbreChemins * aEnd)
Permet de trouver la sortie dans l'arbre des chemins.
Author
Paul Brechenmacher
Date
(January 12th, 2024 6:37 PM)
Parameters
[in] lEnd Ligne d'arrivée trouvée
[in] cEnd Colonne d'arrivée trouvée
[in] aDebut Arbre initial des chemins avec les cases accessibles
[in] aEnd Arbre à l'arrivée du labyrinthe non trouvé
[out] aEnd Arbre à l'arrivée du labyrinthe trouvé
Definition at line 986 of file clem.c.
{
     if(aDebut->positions[0] == lEnd && aDebut->positions[1] == cEnd){
       (*aEnd) = aDebut;
     }
     for(int n = 0; n < aDebut->nbFils; n++){
         findEndArbre(lEnd,cEnd,aDebut->fils[n],aEnd);
     }
 }
References node::fils, node::nbFils, and node::positions.
Referenced by filAriane2().
freeGame()
freeGame (Jeu * jeu)
Permet de libérer la mémoire.
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:27 AM)
Definition at line 951 of file clem.c.
{
     free(jeu->maze.tabMaze);
     free(jeu->maze.arbreChemin);
     free(jeu->megamaze);
     free(jeu->j.inventaire);
     jeu->j.etatDangerJoueur = ETAT_NON_DANGER;
     jeu->j.etatSobreJoueur = ETAT_NORMAL;
     jeu->j.etatTourRestants = 0;
 }
References Maze::arbreChemin, ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, Joueur::etatTourRestants, Joueur::inventaire, Jeu::j, Jeu::maze, Jeu::megamaze, and Maze::tabMaze.
Referenced by main().
gameOver()
gameOver (int level, int score, int highscore)
Affiche la fin de partie et sauvegarde le highscore dans un CSV.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:59 PM)
Parameters
[in] level Niveau atteint par le joueur au cours de la partie
[in] score Score de la partie
[in] highscore Score le plus haut enregisté dans un CSV
Definition at line 791 of file clem.c.
{
     system("clear");
     saveHighScoreCSV(highScore,score);
     afficherScore(level,score);
     printf("\e[1;92m""⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⡀⠀\n");
     printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣤⠀⠀⠀⢀⣴⣿⡶⠀⣾⣿⣿⡿⠟⠛⠁\n");
     printf("⠀⠀⠀⠀⠀⠀⣀⣀⣄⣀⠀⠀⠀⠀⣶⣶⣦⠀⠀⠀⠀⣼⣿⣿⡇⠀⣠⣿⣿⣿⠇⣸⣿⣿⣧⣤⠀⠀⠀\n");
     printf("⠀⠀⢀⣴⣾⣿⡿⠿⠿⠿⠇⠀⠀⣸⣿⣿⣿⡆⠀⠀⢰⣿⣿⣿⣷⣼⣿⣿⣿⡿⢀⣿⣿⡿⠟⠛⠁⠀⠀\n");
     printf("⠀⣴⣿⡿⠋⠁⠀⠀⠀⠀⠀⠀⢠⣿⣿⣹⣿⣿⣿⣿⣿⣿⡏⢻⣿⣿⢿⣿⣿⠃⣼⣿⣯⣤⣴⣶⣿⡤⠀\n");
     printf("⣼⣿⠏⠀⣀⣠⣤⣶⣾⣷⠄⣰⣿⣿⡿⠿⠻⣿⣯⣸⣿⡿⠀⠀⠀⠁⣾⣿⡏⢠⣿⣿⠿⠛⠋⠉⠀⠀⠀\n");
     printf("⣿⣿⠲⢿⣿⣿⣿⣿⡿⠋⢰⣿⣿⠋⠀⠀⠀⢻⣿⣿⣿⠇⠀⠀⠀⠀⠙⠛⠀⠀⠉⠁⠀⠀⠀⠀⠀⠀⠀\n");
     printf("⠹⢿⣷⣶⣿⣿⠿⠋⠀⠀⠈⠙⠃⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
     printf("⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣴⣶⣦⣤⡀⠀\n");
     printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⣠⡇⢰⣶⣶⣾⡿⠷⣿⣿⣿⡟⠛⣉⣿⣿⣿⠆\n");
     printf("⠀⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⡎⣿⣿⣦⠀⠀⠀⢀⣤⣾⠟⢀⣿⣿⡟⣁⠀⠀⣸⣿⣿⣤⣾⣿⡿⠛⠁⠀\n");
     printf("⠀⠀⠀⠀⣠⣾⣿⡿⠛⠉⢿⣦⠘⣿⣿⡆⠀⢠⣾⣿⠋⠀⣼⣿⣿⣿⠿⠷⢠⣿⣿⣿⠿⢻⣿⣧⠀⠀⠀\n");
     printf("⠀⠀⠀⣴⣿⣿⠋⠀⠀⠀⢸⣿⣇⢹⣿⣷⣰⣿⣿⠃⠀⢠⣿⣿⢃⣀⣤⣤⣾⣿⡟⠀⠀⠀⢻⣿⣆⠀⠀\n");
     printf("⠀⠀⠀⣿⣿⡇⠀⠀⢀⣴⣿⣿⡟⠀⣿⣿⣿⣿⠃⠀⠀⣾⣿⣿⡿⠿⠛⢛⣿⡟⠀⠀⠀⠀⠀⠻⠿⠀⠀\n");
     printf("⠀⠀⠀⠹⣿⣿⣶⣾⣿⣿⣿⠟⠁⠀⠸⢿⣿⠇⠀⠀⠀⠛⠛⠁⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
     printf("⠀⠀⠀⠀⠈⠙⠛⠛⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n""\e[0m");
     sleep(5);
 }
References afficherScore(), and saveHighScoreCSV().
Referenced by main().
getOptions()
getOptions (Options * options, int numOptions)
Récupère à chaque selon la ligne la valeur de l'option afin d'afficher la dernière selectionée.
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:08 AM)
Parameters
[in] options Options enregistré
[in] numOptions Numéro de la ligne (0:skin / 1:mode / 2:niveau)
Returns
Type de l'ancien numId selon la ligne de l'option
Definition at line 890 of file clem.c.
{
     switch (numOptions) {
         case 0:
             return options->typeEmoji;
         case 1:
             return options->typeMode;
         case 2:
             return options->typeLevel;
         default:
             return 0;
     }
 }
References Options::typeEmoji, Options::typeLevel, and Options::typeMode.
Referenced by optionChange().
getScoreCSV()
getScoreCSV (Jeu * Jeu)
Récupère dans le CSV le highscore le plus haut du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu avec le score le plus haut non initialisé
[out] jeu Jeu contenant le score le plus haut enregistré, 0 si le fichier n'existe pas
Definition at line 814 of file clem.c.
{
     FILE* scoreFile = NULL;
     int highScore;
     char ligne[20];
     scoreFile = fopen("./out/score.csv", "r");
     if (scoreFile == NULL) {
         highScore = 0;
         printf("Erreur ouverture fichier \n");
     }else{
         highScore = atoi(fgets(ligne,20,scoreFile));
         fclose(scoreFile);
     }
     jeu->highScore = highScore;
 }
References Jeu::highScore.
Referenced by initJeu().
healthPotionEvent()
healthPotionEvent (Jeu * Jeu)
Permet de réaliser un évenement qui soigne le joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] Jeu Jeu contenant la vie du joueur et l'inventaire du joueur
[out] Jeu Jeu contenant la vie augmentée du joueur ou l'inventaire du joueur modifié
Definition at line 135 of file clem.c.
{
     if(jeu->j.pvHealth > 8){
         ajouterItemInventaire(jeu,HEALTH,"Health Potion");
     }else{
         jeu->j.pvHealth = jeu->j.pvHealth +2;
     }
 }
References ajouterItemInventaire(), HEALTH, Jeu::j, and Joueur::pvHealth.
Referenced by verifEvent().
initJeu()
initJeu (Jeu * jeu)
Permet d'initialiser le jeu.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'intégralité des variables non initialisées du jeu
[out] jeu Jeu initialisé
Definition at line 384 of file clem.c.
                       {
     jeu->maze.typeMaze = 1;
     jeu->posMaze[0] = 1;
     jeu->posMaze[1] = 0;
     jeu->level = 0;
     jeu->score = 0;
     jeu->maze.sizeMaze = INITIALSIZE;
     modeHealth(&jeu->j.pvHealth,jeu->options.typeMode);
     jeu->j.findKeys = 1;
     jeu->j.etatCheckPoint = 1;
     jeu->typeEvent = NONE;
     jeu->j.inventaire = malloc(5*sizeof(Item)); //5 items max
     for(int nbItems = 0;nbItems < 5; nbItems++){
         jeu->j.inventaire[nbItems].type = NONE;
     }
     jeu->maze.tabMaze = NULL;
     getScoreCSV(jeu);
     srand(time(NULL));
 }
References Joueur::etatCheckPoint, Joueur::findKeys, getScoreCSV(), INITIALSIZE, Joueur::inventaire, Jeu::j, Jeu::level, Jeu::maze, modeHealth(), NONE, Jeu::options, Jeu::posMaze, Joueur::pvHealth, Jeu::score, Maze::sizeMaze, Maze::tabMaze, Item::type, Jeu::typeEvent, Maze::typeMaze, and Options::typeMode.
Referenced by main().
initOptions()
initOptions (char **** optionsTab, Options * options)
Permet d'initialiser et d'allouer les options et les tableaux du menu options
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:08 AM)
Parameters
[in] optionsTab Tableaux 2D menu options non alloués
[in] optionsTab Tableaux 2D menu options alloués et initialisés
[in] options Options non initialisées
[out] options Options initialisées par défaut
Definition at line 844 of file clem.c.
{
     options->typeEmoji = 0;
     options->typeLevel = 1;
     options->typeMode = 0;
     (*optionsTab) = malloc(3*sizeof(char**));
     for (int i=0; i<3; i++){
         (*optionsTab)[i]=malloc(4*sizeof(char*));
         for (int j=0; j<4; j++){
         (*optionsTab)[i][j]=malloc(100*sizeof(char));
     }
     }
     (*optionsTab)[0][0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 👾 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 🤡 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 💎 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][3] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 👽 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║  "BWHT"◀ NORMAL ▶"BPUR"  ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║   "BWHT"◀ HARD ▶"BPUR"   ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║   "BWHT"◀ EASY ▶"BPUR"   ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][3] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║  "BWHT"◀ BONUS ▶"BPUR"   ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 3 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 5 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 7 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][3] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 9 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
 }
References BPUR, BWHT, Options::typeEmoji, Options::typeLevel, and Options::typeMode.
Referenced by choixMenu().
jouerJeu()
jouerJeu (Jeu * jeu)
Permet de lancher la partie avec un jeu initialisé
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu initialisé
[out] jeu Jeu terminé
Definition at line 769 of file clem.c.
{
     while(jeu->j.pvHealth > 0){
         if((jeu->level/2)+1 > ((jeu->options.typeLevel+1)*3)-1){ // niveau 1 2 3 4 5 6  7 / level  0 2 4 6 8 10 12  / typ 0 1 2 3 / lvl 3 5 7 9
             jeu->maze.typeMaze = 0;
         }
         if (jeu->maze.typeMaze){
             playMazeSimple(jeu);
         }else{
             playMegaMaze(jeu);
         }
         if(jeu->j.pvHealth > 0){
             free(jeu->maze.tabMaze);
             free(jeu->maze.arbreChemin);
             jeu->level=jeu->level+2;
             jeu->score= jeu->score + (25*jeu->level);
         }
     }
 }
References Maze::arbreChemin, Jeu::j, Jeu::level, Jeu::maze, Jeu::options, playMazeSimple(), playMegaMaze(), Joueur::pvHealth, Jeu::score, Maze::tabMaze, Options::typeLevel, and Maze::typeMaze.
Referenced by main().
jouerMaze()
jouerMaze (Jeu * jeu)
Permet de lancer la partie avec les options sélectionées et de jouer.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] jeu Jeu avec le maze avant déplacement joueur
[out] jeu Jeu après le déplacement joueur
Definition at line 405 of file clem.c.
{
     system("clear");
     afficherScore(jeu->level,jeu->score);
     afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
     afficherInventaire(*jeu);
     eventJoueur(&jeu->typeEvent,&jeu->j);
     deplacementMaze(jeu,&jeu->maze.arbreChemin,&jeu->maze.tabMaze,jeu->j.positions);
 }
References afficherInventaire(), afficherMatrice1(), afficherScore(), Maze::arbreChemin, deplacementMaze(), eventJoueur(), Jeu::j, Jeu::level, Jeu::maze, Jeu::options, Joueur::positions, Jeu::score, Maze::sizeMaze, Maze::tabMaze, Options::typeEmoji, Jeu::typeEvent, and Options::typeMode.
Referenced by playMazeSimple(), and playMegaMaze().
lenInt()
lenInt (int score)
Calcule la longueur d'un entier.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] score Score du joueur
Returns
Longeur de l'entier
Definition at line 304 of file clem.c.
                      {
     int len = 0;
     if (score == 0){
         len = 1;
     }
     while(score != 0){
         score = score/10;
         len++;
     }
     return len;
 }
Referenced by afficherScore().
mazePlacementComplexe()
void mazePlacementComplexe (int *** maze, int taille, Joueur * j, int posMazeL, int posMazeC)
Definition at line 465 of file clem.c.
{
     if(!(posMazeC%2 || posMazeL%2)){
         // 0 / 0 --> 3 0
         // 2 / 2 --> 2 1
         // 0 / 2 --> 3 2
         // 2 / 0 --> 1 0
         switch (posMazeC+posMazeL) {
             case 0:
                 setCheck(maze,taille,3);
                 setCheck(maze,taille,0);
                 break;
             case 2:
                 if(posMazeL == 2){
                     setCheck(maze,taille,1);
                     setCheck(maze,taille,0);;
                 }else{
                     setCheck(maze,taille,3);
                     setCheck(maze,taille,2);
                 }
                 break;
             case 4:
                 setCheck(maze,taille,2);
                 setCheck(maze,taille,1);
                 break;
         }
     }else{
         if(posMazeL%2 && posMazeC%2){ //no 3
             for(int i=0;i<4;i++){
                 setCheck(maze,taille,i);
             }
         }else{
             if(posMazeC == 2){
             setEnd(maze,taille,2);
             setCheck(maze,taille,1);
             setCheck(maze,taille,3);
             setCheck(maze,taille,2);
             }
             if(posMazeC == 0){
                 setCheck(maze,taille,1);
                 setCheck(maze,taille,3);
                 setCheck(maze,taille,0);
                 setStart(maze,taille,2,j);
             }
             if(posMazeC == 1){
                 if(posMazeL == 2){
                     setCheck(maze,taille,1);
                     setCheck(maze,taille,0);
                     setCheck(maze,taille,2);
                 }else{
                     setCheck(maze,taille,3);
                     setCheck(maze,taille,0);
                     setCheck(maze,taille,2);
                 }
             }
         }
     }
 }
References setCheck(), setEnd(), and setStart().
Referenced by creerMegaMaze().
mazePlacementSimple()
void mazePlacementSimple (int *** maze, int taille, Joueur * j)
Definition at line 415 of file clem.c.
{
     int randPlacement = rand() % 4; // 0 1 2 3
     setEnd(maze,taille,randPlacement);
     setStart(maze,taille,randPlacement,j);
 }
References setEnd(), and setStart().
Referenced by creerMaze().
medikitEvent()
medikitEvent (Jeu * jeu)
Permet de réaliser un évenement qui soigne le joueur.
Author
Etienne Massonnet
Date
(January 9th, 2024 5:33 PM)
Parameters
[in] Jeu Jeu contenant la vie du joueur et l'inventaire du joueur
[out] Jeu Jeu contenant la vie augmentée du joueur ou l'inventaire du joueur modifié
Definition at line 143 of file clem.c.
{
     if(jeu->j.pvHealth > 5){
         ajouterItemInventaire(jeu,MEDIKIT,"Medikit");
     }else{
         jeu->j.pvHealth = jeu->j.pvHealth +5;
     }
 }
References ajouterItemInventaire(), Jeu::j, MEDIKIT, and Joueur::pvHealth.
Referenced by verifEvent().
milkPotionEvent()
milkPotionEvent (Jeu * jeu)
Permet d'effectuer l'évenement verre de lait (supprime les effets négatifs du joueur)
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'inventaire et etatSobre/etatDanger du joueur
[out] jeu Jeu contenant l'inventaire et etatSobre/etatDanger du joueur modifié
Definition at line 156 of file clem.c.
{
     if(jeu->j.etatSobreJoueur || jeu->j.etatDangerJoueur){
         jeu->j.etatSobreJoueur=ETAT_NORMAL;
         jeu->j.etatDangerJoueur=ETAT_NON_DANGER;
     }else{
         ajouterItemInventaire(jeu,MILK,"Milk Potion");
     }
 }
References ajouterItemInventaire(), ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, Jeu::j, and MILK.
Referenced by verifEvent().
modeHealth()
void modeHealth (int * pvHealth, int typeMode)
Definition at line 362 of file clem.c.
{
     switch (typeMode) {
         case 0:
             *pvHealth = 10;
             break;
         case 1:
             *pvHealth = 1;
             break;
         case 2:
             *pvHealth = 20;
             break;
         case 3:
             *pvHealth = 10;
             break;
         default:
             printf("Erreur Vie");
             break;
     }
 }
Referenced by initJeu().
naviguerArbreChemins()
naviguerArbreChemins (arbreChemins a, Maze maze, int *** tabAriane, int * x)
(Algo A*) Permet naviguer dans l'arbre et d'incrémenter la valeur x à chaque case et de placer la valeur maximal sur la fin
Author
Paul Brechenmacher
Date
(January 9th, 2024 9:22 PM)
Parameters
[in] a Arbre des chemins avec les cases accessibles
[in] maze Maze contenant la taille du labyrinthe
[in] x Valeur initialisé à 6
[in] tabAriane Tableau 2D initialisé
[out] x Valeur de x incrémenté ou non (accumulateur)
[out] tabAriane Tableau 2D modifié avec des valeurs de x incrementés sur les chemins
Definition at line 963 of file clem.c.
{
     if(a->type == SPACE){
       (*tabAriane)[a->positions[0]][a->positions[1]] = *x;
       (*x)++;
     }else{
       (*tabAriane)[a->positions[0]][a->positions[1]] = maze.sizeMaze*maze.sizeMaze;
     }
     for(int n = 0; n < a->nbFils; n++){
         naviguerArbreChemins(a->fils[n],maze,tabAriane,x);
     }
 }
References node::fils, node::nbFils, node::positions, Maze::sizeMaze, SPACE, and node::type.
Referenced by filAriane2().
optionChange()
void optionChange (Options * options, char *** optionsTab)
Definition at line 903 of file clem.c.
{
     int lecture=0;
     int numOptions = 0;
     int numId = 0;
     while(!lecture){
         printf(reset);
         system("clear");
         printf(BPUR);
         printf("%s",optionsTab[numOptions][numId]);
         saveOptions(options,numOptions,numId);
         switch (deplacementTouche(ETAT_OPTION)) {
             case HAUT:
                 numOptions--;
                 if(numOptions==-1){
                     numOptions=2;
                 }
                 numId = getOptions(options,numOptions);
                 break;
             case BAS:
                 numOptions++;
                 if(numOptions==3){
                     numOptions=0;
                 }
                 numId = getOptions(options,numOptions);
                 break;
             case DROITE:
                 numId++;
                 if(numId==4){
                     numId=0;
                 }
                 break;
             case GAUCHE:
                 numId--;
                 if(numId==-1){
                     numId=3;
                 }
                 break;
             case ENTER:
                 lecture=1;
                 break;
         }
         printf(BGRN);
         // choixMenu(lireMenu());
 }
 }
References BAS, BGRN, BPUR, deplacementTouche(), DROITE, ENTER, ETAT_OPTION, GAUCHE, getOptions(), HAUT, reset, and saveOptions().
Referenced by choixMenu().
placerEvents()
placerEvents (Maze * maze, int level)
Permet de placer les events de manières aléatoire dans le labyrythne.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] maze Labyrinthe déja généré avec une taille définie
[in] level Niveau du joueur pour placer plus ou moins d'events
[out] maze Labyrinthe avec des events
Definition at line 561 of file clem.c.
{
     for(int nbEvents = 0; nbEvents < level; nbEvents++){
         int lrandom = rand() % maze->sizeMaze;
         int crandom = rand() % maze->sizeMaze;
         do{
             lrandom = rand() % maze->sizeMaze;
             crandom = rand() % maze->sizeMaze;
         }while(maze->tabMaze[lrandom][crandom] != SPACE);
         maze->tabMaze[lrandom][crandom] = EVENT;
     }
 }
References EVENT, Maze::sizeMaze, SPACE, and Maze::tabMaze.
Referenced by playMazeSimple(), and playMegaMaze().
placerKeys()
placerKeys (Maze * maze, Joueur * j)
Place les clefs dans les labyrinthes 3x3.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:29 PM)
Parameters
[in] maze Maze contenant le labyrinthe, son type et sa taille
[in] j Joueur initialisé avec 0 clé trouvée
[out] maze Maze contenant le labyrinthe avec la clé placée
Definition at line 574 of file clem.c.
{
         j->findKeys = 0;
         int lrandom = rand() % maze->sizeMaze;
         int crandom = rand() % maze->sizeMaze;
         do{
             lrandom = rand() % maze->sizeMaze;
             crandom = rand() % maze->sizeMaze;
         }while(maze->tabMaze[lrandom][crandom] != SPACE);
             maze->tabMaze[lrandom][crandom] = KEY;
 }
References Joueur::findKeys, KEY, Maze::sizeMaze, SPACE, and Maze::tabMaze.
Referenced by playMegaMaze().
playMazeSimple()
playMazeSimple (Jeu * jeu)
Permet de jouer avec le labyrinthe.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:59 PM)
Parameters
[in] jeu Jeu avec maze, arbreChemins et events créés/placés
[out] jeu Jeu avec maze, arbreChemins modifiés
Definition at line 745 of file clem.c.
{
     creerMaze(jeu);
     //mazeCSV(&jeu->maze);
     placerEvents(&jeu->maze,jeu->level);
     while(jeu->maze.arbreChemin->type && jeu->j.pvHealth > 0){
         jouerMaze(jeu);
     }
 }
References Maze::arbreChemin, creerMaze(), Jeu::j, jouerMaze(), Jeu::level, Jeu::maze, placerEvents(), Joueur::pvHealth, and node::type.
Referenced by jouerJeu().
playMegaMaze()
playMegaMaze (Jeu * jeu)
Permet de jouer avec les labyrinthes 3x3.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:59 PM)
Parameters
[in] jeu Jeu avec maze, arbreChemins et events clefs créés/placés
[out] jeu Jeu avec maze, arbreChemins modifiés
Definition at line 753 of file clem.c.
{
     creerMegaMaze(jeu);
     jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]];
     jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
     for(int i = 0; i < 3 ;i++){
         for(int j = 0; j < 3;j++){
             placerEvents(&jeu->megamaze[i][j],jeu->level/2);
             //mazebigCSV(&jeu->megamaze[i][j],i,j);
             }
         }
     placerKeys(&jeu->megamaze[rand() % 3][rand() % 3],&jeu->j);
     while((!jeu->j.findKeys || jeu->maze.arbreChemin->type) && jeu->j.pvHealth > 0){
         jouerMaze(jeu);
     }
 }
References Maze::arbreChemin, creerArbreChemins(), creerMegaMaze(), Joueur::findKeys, Jeu::j, jouerMaze(), Jeu::level, Jeu::maze, Jeu::megamaze, placerEvents(), placerKeys(), Joueur::positions, Jeu::posMaze, Joueur::pvHealth, Maze::sizeMaze, Maze::tabMaze, and node::type.
Referenced by jouerJeu().
remonterArbre()
remonterArbre (arbreChemins a, int ** tabAriane, Jeu * jeu)
Permet de trouver le chemins le plus court (algo A*), en prenant toujours la plus petite valeur aux alentours.
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:27 AM)
Parameters
[in] tabAriane Arbre à l'arrivée du labyrinthe trouvé
[in] a Arbre à l'arrivée/la fin du labyrinthe
[in] jeu Jeu contenant le labyrinthe
[out] jeu Jeu contenant le labyrinthe avec le fil d'Ariane visible
Definition at line 995 of file clem.c.
{
     // system("clear");
     // afficherScore(jeu->level,jeu->score);
     // afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji);
     // afficherInventaire(*jeu);
     // usleep(5000);
     if(tabAriane[a->positions[0]][a->positions[1]] != 6){
       int valMin = tabAriane[a->positions[0]][a->positions[1]];
       int idMin = 0;
       for(int n = 0; n < a->nbFils; n++){
         if(tabAriane[a->fils[n]->positions[0]][a->fils[n]->positions[1]]<valMin){
           valMin = tabAriane[a->fils[n]->positions[0]][a->fils[n]->positions[1]];
           idMin = n;
         }
       }
       if(tabAriane[a->parent->positions[0]][a->parent->positions[1]]<valMin){
         valMin = tabAriane[a->parent->positions[0]][a->parent->positions[1]];
         idMin = 4;
       }
       if(idMin == 4){
         if(jeu->maze.tabMaze[a->parent->positions[0]][a->parent->positions[1]] == SPACE){
             jeu->maze.tabMaze[a->parent->positions[0]][a->parent->positions[1]] = FIL;
         }
         remonterArbre(a->parent,tabAriane,jeu);
       }else{
          if(jeu->maze.tabMaze[a->fils[idMin]->positions[0]][a->fils[idMin]->positions[1]] == SPACE){
             jeu->maze.tabMaze[a->fils[idMin]->positions[0]][a->fils[idMin]->positions[1]] = FIL;
         }
         remonterArbre(a->fils[idMin],tabAriane,jeu);
       }
   }
 }
References FIL, node::fils, Jeu::maze, node::nbFils, node::parent, node::positions, SPACE, and Maze::tabMaze.
Referenced by filAriane2().
saveHighScoreCSV()
saveHighScoreCSV (int highScore, int newscore)
Enregistre dans le CSV le highscore le plus haut du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] highScore Plus haut score réalisé par le joueur
[in] newscore Score de la partie actuelle
Definition at line 829 of file clem.c.
{
     FILE* scoreFile = NULL;
     scoreFile = fopen("./out/score.csv", "w");
     if (scoreFile == NULL) {
         printf("Erreur ouverture fichier \n");
     }else{
         if(score > highScore){
             fprintf(scoreFile,"%d",score);
         }else{
             fprintf(scoreFile,"%d",highScore);
         }
         fclose(scoreFile);
     }
 }
Referenced by gameOver().
saveOptions()
saveOptions (Options * options, int numOptions, int numId)
Permet de sauvegarder l'option selon la ligne et la valeur numId(choix du joueur pour une option)
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:08 AM)
Parameters
[in] options Options enregistré
[in] numOptions Numéro de la ligne (0:skin / 1:mode / 2:niveau)
[in] numId Numéro du type voulu pour l'option (ex emoji : 0 : 👾)
[out] options Options modifié
Definition at line 876 of file clem.c.
{
     switch (numOptions) {
         case 0:
             options->typeEmoji = numId;
             break;
         case 1:
             options->typeMode = numId;
             break;
         case 2:
             options->typeLevel = numId;
             break;
     }
 }
References Options::typeEmoji, Options::typeLevel, and Options::typeMode.
Referenced by optionChange().
scorePrint()
scorePrint (int scoreLen)
Permet d'espacer correctement seulement la taille du score du joueur
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] scorelen Longueur de l'entier score
Definition at line 316 of file clem.c.
{
     while(scoreLen < 5){
         printf(" ");
         scoreLen++;
     }
     printf("    ║\n");
 }
Referenced by afficherScore().
setCheck()
void setCheck (int *** maze, int taille, int randPlacement)
Definition at line 423 of file clem.c.
{
     int random = 0;
     random = 1 + rand() % ( taille - 2 );
     // Vérifier que la case choisie est vide (pas un mur)
     // Marquer la case de départ dans la matrice et la retourner
     switch (randPlacement) {
         case 2:
                 while ( (*maze)[ random ][ 1 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ 0 ] = CHECKPOINT;
             break;
         case 3:
             while ( (*maze)[ taille - 2  ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ taille - 1 ][ random ] = CHECKPOINT;
             break;
         case 0:
                 while ( (*maze)[ random ][ taille - 2 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ taille - 1 ] = CHECKPOINT;
             break;
         case 1:
             while ( (*maze)[ 1 ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ 0 ][ random ] = CHECKPOINT;
             break;
         default:
             break;
     }
 }
References CHECKPOINT, and SPACE.
Referenced by mazePlacementComplexe().
useItem()
useItem (Jeu * jeu, int typeInput)
Permet d'utiliser un item dans son inventaire.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] typeInput Numéro de la touche appuyée pour utiliser un objet
[in] jeu Jeu avec inventaire avec l'item utilisé
[out] jeu Jeu avec inventaire sans l'item utilisé
Definition at line 344 of file clem.c.
{
     switch (jeu->j.inventaire[typeInput].type){
         case HEALTH:
             jeu->j.pvHealth = jeu->j.pvHealth +2;
             break;
         case MEDIKIT:
             jeu->j.pvHealth = jeu->j.pvHealth +5;
             break;
         case MILK:
             jeu->j.etatSobreJoueur = ETAT_NORMAL;
             jeu->j.etatDangerJoueur = ETAT_NON_DANGER;
             break;
         default:
             break;
     }
     jeu->j.inventaire[typeInput].type = NONE;
 }
References ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, HEALTH, Joueur::inventaire, Jeu::j, MEDIKIT, MILK, NONE, Joueur::pvHealth, and Item::type.
Referenced by deplacementMaze().
verifCheck()
void verifCheck (Jeu * jeu, int ** maze, int positionL, int positionC)
Definition at line 605 of file clem.c.
{
     if(positionL > -1 && positionC > -1 && positionC < jeu->maze.sizeMaze && positionL < jeu->maze.sizeMaze){
         if((maze[positionL][positionC]) == CHECKPOINT){
             jeu->j.etatCheckPoint = 0;
             jeu->maze.tabMaze[jeu->j.positions[0]][jeu->j.positions[1]] = SPACE;
             if(positionC == 0){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]-1];
                 jeu->posMaze[1]--;
                 findCheck(jeu,jeu->maze.sizeMaze-1,1);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionL == 0){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]-1][jeu->posMaze[1]];
                 jeu->posMaze[0]--;
                 findCheck(jeu,jeu->maze.sizeMaze-1,0);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionC == (jeu->maze.sizeMaze-1)){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]+1];
                 jeu->posMaze[1]++;
                 afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
                 findCheck(jeu,0,1);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionL == (jeu->maze.sizeMaze-1)){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]+1][jeu->posMaze[1]];
                 jeu->posMaze[0]++;
                 findCheck(jeu,0,0);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
         }
     }
 }
References afficherMatrice1(), Maze::arbreChemin, CHECKPOINT, creerArbreChemins(), Joueur::etatCheckPoint, findCheck(), Jeu::j, Jeu::maze, Jeu::megamaze, Jeu::options, Joueur::positions, Jeu::posMaze, Maze::sizeMaze, SPACE, Maze::tabMaze, Options::typeEmoji, and Options::typeMode.
Referenced by deplacementMaze().
verifEtatEvent()
verifEtatEvent (Joueur * j, int * typeEvent)
Vérifie l'état de l'évenement pour l'affichage et la fin du poison et du feu.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] j Pointeur du Joueur contenant les caractéristiques et les états du joueur
[in] typeEvent Type de l'event à effectuer et à vérifier
[out] j Joueur modifié avec un nouvel état (souvent le poison ou le feu)
Definition at line 286 of file clem.c.
{
     // Afficher l'event en cours si pas NONE et si le joueur n'est pas en poison ou en feu
     if(*typeEvent != NONE && j->etatDangerJoueur == ETAT_NON_DANGER){
                 afficherUseItem(*typeEvent);
                 *typeEvent = NONE;
     }
     //Si le nombre de tours de poison et de feu est terminé
     if(j->etatTourRestants == 0){
         j->etatDangerJoueur = ETAT_NORMAL;
     }
 }
References afficherUseItem(), ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatTourRestants, and NONE.
Referenced by eventJoueur().
verifEvent()
verifEvent (Jeu * jeu, int *** maze, int positionL, int positionsC)
Vérifie si un event est placé sur la case demandé par le joueur et effectue un évenement aléatoirement.
Author
Paul Brechenmacher
Date
(January 12th, 2024 5:32 PM)
Parameters
[in] jeu Jeu contenant l'inventaire et les différentes options
[in] maze Pointeur du tableau 2D représentant le labyrinthe
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
Definition at line 166 of file clem.c.
{
     if((*maze)[positionL][positionC] == EVENT){
         jeu->score = jeu->score + 25;
         int precEvent =-1;
         int randomEvent;
         usleep(5000);
         // pas remettre l'inversion clavier si on l'a pas enlevé avant
         do{
             randomEvent = (rand() % 10)+1; // entre random entre 1 et 10
         }while (precEvent==randomEvent);
         precEvent = randomEvent;
         switch (randomEvent) {
             case HEALTH:
                 healthPotionEvent(jeu);
                 break;
             case MEDIKIT:
                 medikitEvent(jeu);
                 break;
             case DAMAGE:
                 damageTrapEvent(jeu);
                 break;
             case FIRE:
                 jeu->j.etatDangerJoueur = ETAT_FEU;
                 jeu->j.etatTourRestants = jeu->j.etatTourRestants + (jeu->level/4)+1;
                break;
             case DRUNK:
                 jeu->j.etatSobreJoueur=ETAT_DRUNK;
                 precEvent=1;
                 break;
             case MILK:
                 milkPotionEvent(jeu);
                 break;
             case ARIANE:
                 if(jeu->maze.typeMaze){
                     filAriane2(jeu);
                 }
                 break;
             case POISON:
                 jeu->j.etatDangerJoueur = ETAT_POISON;
                 jeu->j.etatTourRestants = jeu->j.etatTourRestants + (jeu->level/4)+2;
                 break;
             case SCORE:
                 jeu->score = jeu->score + 500;
                 break;
             case FUN:
                 if(jeu->options.typeEmoji == 1 && jeu->options.typeMode == 3){
                     system("clear");
                     lireArsenal();
                     sleep(5);
                     system("clear");
                 }else{
                     jeu->score = jeu->score + 250;
                 }
                 break;
             default:
                 printf("Error Event Switch Case\n");
                 break;
         }
         jeu->typeEvent = randomEvent;
     }
     if((*maze)[positionL][positionC] == KEY){
         jeu->j.findKeys = 1;
         jeu->score = jeu->score + 100;
     }
 }
References ARIANE, DAMAGE, damageTrapEvent(), DRUNK, ETAT_DRUNK, ETAT_FEU, ETAT_POISON, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, Joueur::etatTourRestants, EVENT, filAriane2(), Joueur::findKeys, FIRE, FUN, HEALTH, healthPotionEvent(), Jeu::j, KEY, Jeu::level, lireArsenal(), Jeu::maze, MEDIKIT, medikitEvent(), MILK, milkPotionEvent(), Jeu::options, POISON, SCORE, Jeu::score, Options::typeEmoji, Jeu::typeEvent, Maze::typeMaze, and Options::typeMode.
Referenced by deplacementMaze().
verifPoisonFeu()
verifPoisonFeu (Joueur * j)
Permet d'effectuer les évenements poison et feu en influant sur la vie du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] j Joueur contenant sa vie et son nombre de tours restant avec EtatDanger != 0
[out] j Joueur avec vie modifié et nombre de tours restant modifié
Definition at line 271 of file clem.c.
{
     if(j->etatDangerJoueur != ETAT_NON_DANGER){
             if(j->etatDangerJoueur == ETAT_POISON){
                 afficherUseItem(POISON);
                 j->pvHealth--;
                 j->etatTourRestants--;
             }
             if(j->etatDangerJoueur == ETAT_FEU){
                 j->pvHealth--;
                 afficherUseItem(FIRE);
                 j->etatTourRestants--;
             }
         }
 }
References afficherUseItem(), ETAT_FEU, ETAT_NON_DANGER, ETAT_POISON, Joueur::etatDangerJoueur, Joueur::etatTourRestants, FIRE, POISON, and Joueur::pvHealth.
Referenced by eventJoueur().