ProjetP1: etienne.c File Reference
etienne.c File Reference
#include "etienne.h"
#include "paul.h"
#include "clem.h"
#include "structure.h"
#include <stdio.h>
#include <stdlib.h>
Functions
char ** lireMenu ()
Prépare l'affichage du menu de début de jeu.
void choixMenu (char **menus, Options *options)
Affiche le menu et propose de naviguer entre les 3 choix possibles.
void regle (Options *options)
affiche les règles du jeu
Function Documentation
choixMenu()
choixMenu (char ** menus, Options * options)
Affiche le menu et propose de naviguer entre les 3 choix possibles.
Author
Etienne Massonnet
Date
(January 9th, 2024 5:00 PM)
Definition at line 25 of file etienne.c.
{
     printf(BGRN);
     char*** optionsTab = NULL;
     initOptions(&optionsTab,options);
     int numMenu = 0;
     int jeuLance = 0;
     while (!jeuLance){
         system("clear");
         printf("%s", menus[numMenu]);
         switch (deplacementTouche(ETAT_MENU)) {
             case HAUT:
                 numMenu--;
                 if(numMenu==-1){
                     numMenu=2;
                 }
                 break;
             case BAS:
                 numMenu++;
                 if(numMenu==3){
                     numMenu=0;
                 }
                 break;
             case ENTER:
                 switch (numMenu) {
                     case 0:
                         jeuLance = 1;
                         break;
                     case 1:
                         optionChange(options,optionsTab);
                         break;
                     case 2:
                         regle(options);
                         break;
                 }
                 // jeuLance=1;
                 break;
             default:
                 break;
         }
         //return numMenu;
         //renvoie 0 pour jouer, 1 pour options et 2 pour règles
     }
     printf(reset);
 }
References BAS, BGRN, deplacementTouche(), ENTER, ETAT_MENU, HAUT, initOptions(), optionChange(), regle(), and reset.
Referenced by main(), and regle().
lireMenu()
lireMenu ()
Prépare l'affichage du menu de début de jeu.
Author
Etienne Massonnet
Date
(January 9th, 2024 5:00 PM)
Definition at line 8 of file etienne.c.
                  {
     //allocation de la mémoire
     char** menus;
     menus = malloc(3*sizeof(char*));
     for (int i=0; i<3; i++){
         menus[i]=malloc(100*sizeof(char));
     }
     menus[0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< WCKD >"BGRN"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║ "BWHT"▶ JOUER    ◀ "BGRN"║  ╔════════╣\n║  ╠══╗  ║  ║   OPTIONS    ║  ║  ════  ║\n║     ║  ║  ║   RÈGLES     ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     menus[1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< WCKD >"BGRN"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   JOUER      ║  ╔════════╣\n║  ╠══╗  ║  ║ "BWHT"▶ OPTIONS  ◀"BGRN" ║  ║  ════  ║\n║     ║  ║  ║   RÈGLES     ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     menus[2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< WCKD >"BGRN"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   JOUER      ║  ╔════════╣\n║  ╠══╗  ║  ║   OPTIONS    ║  ║  ════  ║\n║     ║  ║  ║ "BWHT"▶ RÈGLES   ◀"BGRN" ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     return menus;
 }
References BGRN, and BWHT.
Referenced by main(), and regle().
regle()
regle (Options * options)
affiche les règles du jeu
Author
Paul Brechenmacher
Date
(January 9th, 2024 5:00 PM)
Definition at line 74 of file etienne.c.
{
     int lecture=0;
     while(!lecture){
         system("clear");
         printf("\e[4;33m""\nLe Labyrinthe :");
         printf("\n\n""\e[0m""\e[1;97m""Le jeu est plutôt simple et facile à comprendre.\nIl suffit de déplacer le robot jusqu'à l'arrivée.\n\n""\e[1;32m""Les déplacements sont réalisés en utilisant :\n - Z pour aller vers le haut\n - Q pour aller vers la gauche\n - S pour aller vers le bas\n - D pour aller vers la droite\n\n Sur votre route, vous aurez la possibilité de récupérer des bonus ou des malus : \n - Maj Gauche + 1/2/3/4/5 pour utiliser l'item\n\n""\e[0;97m""Ce jeu a été realisé par Paul Brechenmacher, Paul Le Blanc, Etienne Massonnet et Gabin Alquier pour un projet de fin de semestre en 2023-2024.\n");
         printf("\n\n Pour quitter et lancer le jeu, appuyez sur 'Entrée'""\e[0m ");
         switch(deplacementTouche(ETAT_ENTER)){
             case ENTER:
                 lecture=1;
                 break;
         }
     }
     choixMenu(lireMenu(),options);
 }
References choixMenu(), deplacementTouche(), ENTER, ETAT_ENTER, and lireMenu().
Referenced by choixMenu().