Projet P2 : The Maze: event.h File Reference
event.h File Reference
#include "structure.h"
Functions
void emptyBuffer ()
vide le buffer
char deplacementTouche (int etatJoueur)
Permet de capturer une touche utilisée par l'utilisateur et interprète cette entrée en fonction de l'état du joueur fourni et qui renvoie la touche pressée.
void mazeCSV (Maze *maze)
permet d'écrire le contenue de la structure Maze dans un fichier CSV "maze.csv" placé dans le repertoire "out/"
void mazebigCSV (Maze *megamaze, int i, int j)
megamaze est un labyrinthe de plusieurs labyrinthe et cette fonction permet d'écrire le contenue des différents labyrinthes dans des fichiers CSV "maze<i><j>.csv" placé dans le repertoire "out/megaMazeCSV/" \parameters pointeur vers la structure Maze, entier i, entier j
void afficherMaze (Maze *maze)
affiche le labyrinthe contenue dans la structure Maze dans la console \parameters pointeur vers la structure Maze
void healthPotionEvent (Jeu *jeu)
Permet de réaliser un évenement qui soigne le joueur.
void medikitEvent (Jeu *jeu)
Permet de réaliser un évenement qui soigne le joueur.
void damageTrapEvent (Jeu *jeu)
Permet d'effectuer l'évenement de dégats sur le joueur.
void milkPotionEvent (Jeu *jeu)
Permet d'effectuer l'évenement verre de lait (supprime les effets négatifs du joueur)
int notSoRandom (Jeu *jeu)
Modifie l'aléatoire pour une apparition des objets plus équilibrée.
void naviguerArbreChemins (arbreChemins a, Maze maze, int ***tabAriane, int *x)
(Algo A*) Permet naviguer dans l'arbre et d'incrémenter la valeur x à chaque case et de placer la valeur maximal sur la fin
void findEnd (int **tabAriane, int *lEnd, int *cEnd, int taille)
Permet de trouver la sortie du tabArianne.
void findEndArbre (int lEnd, int cEnd, arbreChemins aDebut, arbreChemins *aEnd)
Permet de trouver la sortie dans l'arbre des chemins.
void remonterArbre (arbreChemins a, int **tabAriane, Jeu *jeu)
Permet de trouver le chemins le plus court (algo A*), en prenant toujours la plus petite valeur aux alentours.
void filAriane2 (Jeu *jeu)
Permet d'afficher le fil d'Ariane.
void verifEvent (Jeu *jeu, int ***maze, int positionL, int positionC)
Vérifie si un event est placé sur la case demandé par le joueur et effectue un évenement aléatoirement.
void eventJoueur (int *typeEvent, Joueur *j)
Effectue l'event en vérifiant son type et l'état du joueur (souvent le poison ou le feu)
void ajouterItemInventaire (Jeu *jeu, int type, char *name)
Ajoute un objet dans l'inventaire du joueur.
void verifPoisonFeu (Joueur *j)
Permet d'effectuer les évenements poison et feu en influant sur la vie du joueur.
void verifEtatEvent (Joueur *j, int *typeEvent)
Vérifie l'état de l'évenement pour l'affichage et la fin du poison et du feu.
Variables
int inversion
Function Documentation
afficherMaze()
void afficherMaze (Maze * maze)
affiche le labyrinthe contenue dans la structure Maze dans la console \parameters pointeur vers la structure Maze
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Parameters
[in] maze vers la structure Maze
Definition at line 205 of file event.c.
{
     for (int i = 0; i < maze->sizeMaze; i++) {
         for (int j = 0; j < maze->sizeMaze; j++) {
             printf("%2d ", maze->tabMaze[i][j]);
         }
         printf("\n");
     }
 }
References Maze::sizeMaze, and Maze::tabMaze.
ajouterItemInventaire()
void ajouterItemInventaire (Jeu * jeu, int type, char * name)
Ajoute un objet dans l'inventaire du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'inventaire
[in] type Type de l'objet à ajouter
[in] name Nom de l'objet à ajouter
[out] jeu Jeu contenant l'inventaire avec le nouvel item
Definition at line 214 of file event.c.
{
     int nbItems = 0;
     while(jeu->j.inventaire[nbItems].type != NONE){
         nbItems++;
     }
     jeu->j.inventaire[nbItems].type = type;
     jeu->j.inventaire[nbItems].name = name;
 }
References Joueur::inventaire, Jeu::j, Item::name, NONE, and Item::type.
Referenced by healthPotionEvent(), medikitEvent(), and milkPotionEvent().
damageTrapEvent()
void damageTrapEvent (Jeu * jeu)
Permet d'effectuer l'évenement de dégats sur le joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant la vie du joueur
[out] jeu Jeu contenant la vie du joueur modifiée
Definition at line 245 of file event.c.
{
     jeu->j.pvHealth--;
 }
References Jeu::j, and Joueur::pvHealth.
Referenced by verifEvent().
deplacementTouche()
char deplacementTouche (int etatJoueur)
Permet de capturer une touche utilisée par l'utilisateur et interprète cette entrée en fonction de l'état du joueur fourni et qui renvoie la touche pressée.
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Parameters
[in] etatJoueur représentant l'etat du joueur (ETAT_ENTER, ETAT_OPTION, ETAT_MENU, ETAT_DRUNK)
Returns
caractère (touche pressée)
Definition at line 11 of file event.c.
{
   struct termios tty_opts_backup, tty_opts_raw;
   char c;
   int pastermine=1;//par défaut on le met à vrai
   // Back up current TTY settings
   tcgetattr(STDIN_FILENO, &tty_opts_backup);
   // Change TTY settings mode
   cfmakeraw(&tty_opts_raw);
   tcsetattr(STDIN_FILENO, TCSANOW, &tty_opts_raw);
   while (pastermine) {
     c = getchar();
     if (etatJoueur == ETAT_ENTER){
       switch(c){
         case ENTER:
           pastermine =0;
           break;
         default:
           break;
       }
     }
     if (etatJoueur == ETAT_OPTION) {
       switch (c) {
         case HAUT:
           pastermine = 0;
           break;
         case BAS:
           pastermine = 0;
           break;
         case ENTER:
           pastermine = 0;
           break;
         case DROITE:
           pastermine = 0;
           break;
         case GAUCHE:
           pastermine = 0;
           break;
         default:
           break;
       }
     }
     if (etatJoueur == ETAT_MENU) {
       switch (c) {
         case HAUT:
           pastermine = 0;
           break;
         case BAS:
           pastermine = 0;
           break;
         case ENTER:
           pastermine = 0;
           break;
         default:
           break;
       }
     }
     if (etatJoueur == ETAT_DRUNK) {
       switch (c) {
         case HAUT:
           c = BAS;
           pastermine = 0;
           break;
         case GAUCHE:
           c = DROITE;
           pastermine = 0;
           break;
         case DROITE:
           c = GAUCHE;
           pastermine = 0;
           break;
         case BAS:
           c = HAUT;
           pastermine = 0;
           break;
         case HOTBAR1:
           pastermine=0;
           break;
         case HOTBAR2:
           pastermine=0;
           break;
         case HOTBAR3:
           pastermine=0;
           break;
         case HOTBAR4:
           pastermine=0;
           break;
         case HOTBAR5:
           pastermine=0;
           break;
         default:
           break;
       }
     }
     switch(c){
       case HAUT:
         pastermine=0;
         break;
       case GAUCHE:
         pastermine=0;
         break;
       case DROITE:
         pastermine=0;
         break;
       case BAS:
         pastermine=0;
         break;
       case HOTBAR1:
         pastermine=0;
         break;
       case HOTBAR2:
         pastermine=0;
         break;
       case HOTBAR3:
         pastermine=0;
         break;
       case HOTBAR4:
         pastermine=0;
         break;
       case HOTBAR5:
         pastermine=0;
         break;
       case 97:
         printf("\n Vous avez tapé la lettre %c qui permet de quitter le programme!",c);
         /* NE PAS OUBLIER : sinon on ne peut plus écrire dans le terminal */
         // Restore previous TTY settings
         tcsetattr(STDIN_FILENO, TCSANOW, &tty_opts_backup);
         printf("\n");
         exit(0);
       default:
         printf("NON prise en compte\r\n");
         break;
     }
   }
   /* NE PAS OUBLIER : sinon on ne peut plus écrire dans le terminal */
   // Restore previous TTY settings
   tcsetattr(STDIN_FILENO, TCSANOW, &tty_opts_backup);
   return c;
 }
References BAS, DROITE, ENTER, ETAT_DRUNK, ETAT_ENTER, ETAT_MENU, ETAT_OPTION, GAUCHE, HAUT, HOTBAR1, HOTBAR2, HOTBAR3, HOTBAR4, and HOTBAR5.
Referenced by choixMenu(), deplacementMaze(), optionChange(), and regle().
emptyBuffer()
void emptyBuffer ()
vide le buffer
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Definition at line 6 of file event.c.
                    {
   char c;
   while (((c = getchar()) != '\n') && (c != EOF));
 }
eventJoueur()
void eventJoueur (int * typeEvent, Joueur * j)
Effectue l'event en vérifiant son type et l'état du joueur (souvent le poison ou le feu)
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] j Pointeur du Joueur contenant les caractéristiques et les états du joueur
[in] typeEvent Type de l'event à effectuer et à vérifier
[out] j Joueur modifié avec un nouvel état (souvent le poison ou le feu)
Definition at line 386 of file event.c.
{
     verifEtatEvent(j,typeEvent);
     verifPoisonFeu(j);
 }
References verifEtatEvent(), and verifPoisonFeu().
Referenced by jouerMaze().
filAriane2()
void filAriane2 (Jeu * jeu)
Permet d'afficher le fil d'Ariane.
Author
Paul Brechenmacher
Date
(January 9th, 2024 9:22 PM)
Precondition
Le labyrinthe doit être sans les checkpoints (typeMaze = 1)
Parameters
[in] jeu Jeu contenant le labyrinthe
[out] jeu Jeu contenant le labyrinthe avec le fil d'Ariane visible
Definition at line 474 of file event.c.
{
     int x = 6;
     int** tabAriane = NULL;
     int cEnd,lEnd;
     allouerTab2(&tabAriane,jeu->maze.sizeMaze);
     naviguerArbreChemins(jeu->maze.arbreCheminDepart,jeu->maze,&tabAriane,&x);
     findEnd(tabAriane,&lEnd,&cEnd,jeu->maze.sizeMaze);
     arbreChemins aEnd = malloc(sizeof(node*));
     findEndArbre(lEnd,cEnd,jeu->maze.arbreCheminDepart,&aEnd);
     remonterArbre(aEnd,tabAriane,jeu);
 }
References allouerTab2(), Maze::arbreCheminDepart, findEnd(), findEndArbre(), Jeu::maze, naviguerArbreChemins(), remonterArbre(), and Maze::sizeMaze.
Referenced by verifEvent().
findEnd()
void findEnd (int ** tabAriane, int * lEnd, int * cEnd, int taille)
Permet de trouver la sortie du tabArianne.
Author
Paul Brechenmacher
Date
(January 12th, 2024 6:37 PM)
Parameters
[in] tabAriane Tableau avec des valeurs de x incrementés sur les chemins
[in] lEnd Ligne d'arrivée non trouvée
[in] cEnd Colonne d'arrivée non trouvée
[in] taille Taille labyrinthe
[out] lEnd Ligne d'arrivée trouvée
[out] cEnd Colonne d'arrivée trouvée
Definition at line 425 of file event.c.
{
   for(int i = 0; i < taille; i++) {
     for (int j = 0; j < taille; j++) {
       if(tabAriane[i][j] == taille*taille){
         *lEnd = i;
         *cEnd = j;
       }
      }
   }
 }
Referenced by filAriane2().
findEndArbre()
void findEndArbre (int lEnd, int cEnd, arbreChemins aDebut, arbreChemins * aEnd)
Permet de trouver la sortie dans l'arbre des chemins.
Author
Paul Brechenmacher
Date
(January 12th, 2024 6:37 PM)
Parameters
[in] lEnd Ligne d'arrivée trouvée
[in] cEnd Colonne d'arrivée trouvée
[in] aDebut Arbre initial des chemins avec les cases accessibles
[in] aEnd Arbre à l'arrivée du labyrinthe non trouvé
[out] aEnd Arbre à l'arrivée du labyrinthe trouvé
Definition at line 435 of file event.c.
{
     if(aDebut->positions[0] == lEnd && aDebut->positions[1] == cEnd){
       (*aEnd) = aDebut;
     }
     for(int n = 0; n < aDebut->nbFils; n++){
         findEndArbre(lEnd,cEnd,aDebut->fils[n],aEnd);
     }
 }
References node::fils, node::nbFils, and node::positions.
Referenced by filAriane2().
healthPotionEvent()
void healthPotionEvent (Jeu * jeu)
Permet de réaliser un évenement qui soigne le joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] Jeu Jeu contenant la vie du joueur et l'inventaire du joueur
[out] Jeu Jeu contenant la vie augmentée du joueur ou l'inventaire du joueur modifié
Definition at line 229 of file event.c.
{
     if(jeu->j.pvHealth > 8){
         ajouterItemInventaire(jeu,HEALTH,"Health Potion");
     }else{
         jeu->j.pvHealth = jeu->j.pvHealth +2;
     }
 }
References ajouterItemInventaire(), HEALTH, Jeu::j, and Joueur::pvHealth.
Referenced by verifEvent().
mazebigCSV()
void mazebigCSV (Maze * maze, int i, int j)
megamaze est un labyrinthe de plusieurs labyrinthe et cette fonction permet d'écrire le contenue des différents labyrinthes dans des fichiers CSV "maze<i><j>.csv" placé dans le repertoire "out/megaMazeCSV/" \parameters pointeur vers la structure Maze, entier i, entier j
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Parameters
[in] megamaze,i,j vers la structure Maze et la ligne et la colonne du maze
Definition at line 187 of file event.c.
{
     char fichiers[40];
     snprintf(fichiers, sizeof(fichiers), "./out/megaMazeCSV/maze%d%d.csv",i,j);
     FILE *fichier = fopen(fichiers, "w");
     if (fichier == NULL) {
         printf("Impossible d'ouvrir le fichier");
     }
     for(int i=0;i<maze->sizeMaze;i++){
       for(int j=0;j<maze->sizeMaze;j++){
         fprintf(fichier,"%d ",maze->tabMaze[i][j]);
       }
       fprintf(fichier, "\n");
     }
     fclose(fichier);
 }
References Maze::sizeMaze, and Maze::tabMaze.
mazeCSV()
void mazeCSV (Maze * maze)
permet d'écrire le contenue de la structure Maze dans un fichier CSV "maze.csv" placé dans le repertoire "out/"
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Parameters
[in] maze vers la structure Maze
Definition at line 170 of file event.c.
{
     FILE *fichier = fopen("out/maze.csv", "w");
     if (fichier == NULL) {
         printf("Impossible d'ouvrir le fichier");
     }
     for(int i=0;i<(maze->sizeMaze);i++){
       for(int j=0;j<(maze->sizeMaze);j++){
         fprintf(fichier,"%d ",maze->tabMaze[i][j]);
       }
       fprintf(fichier, "\n");
     }
     fclose(fichier);
 }
References Maze::sizeMaze, and Maze::tabMaze.
medikitEvent()
void medikitEvent (Jeu * jeu)
Permet de réaliser un évenement qui soigne le joueur.
Author
Etienne Massonnet
Date
(January 9th, 2024 5:33 PM)
Parameters
[in] Jeu Jeu contenant la vie du joueur et l'inventaire du joueur
[out] Jeu Jeu contenant la vie augmentée du joueur ou l'inventaire du joueur modifié
Definition at line 237 of file event.c.
{
     if(jeu->j.pvHealth > 5){
         ajouterItemInventaire(jeu,MEDIKIT,"Medikit");
     }else{
         jeu->j.pvHealth = jeu->j.pvHealth +5;
     }
 }
References ajouterItemInventaire(), Jeu::j, MEDIKIT, and Joueur::pvHealth.
Referenced by verifEvent().
milkPotionEvent()
void milkPotionEvent (Jeu * jeu)
Permet d'effectuer l'évenement verre de lait (supprime les effets négatifs du joueur)
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'inventaire et etatSobre/etatDanger du joueur
[out] jeu Jeu contenant l'inventaire et etatSobre/etatDanger du joueur modifié
Definition at line 250 of file event.c.
{
     if(jeu->j.etatSobreJoueur || jeu->j.etatDangerJoueur){
         if(jeu->j.etatSobreJoueur && jeu->options.typeMode == 4){
             jeu->j.visionRange++;
         }
         jeu->j.etatSobreJoueur=ETAT_NORMAL;
         jeu->j.etatDangerJoueur=ETAT_NON_DANGER;
     }else{
         ajouterItemInventaire(jeu,MILK,"Milk Potion");
     }
 }
References ajouterItemInventaire(), ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, Jeu::j, MILK, Jeu::options, Options::typeMode, and Joueur::visionRange.
Referenced by verifEvent().
naviguerArbreChemins()
void naviguerArbreChemins (arbreChemins a, Maze maze, int *** tabAriane, int * x)
(Algo A*) Permet naviguer dans l'arbre et d'incrémenter la valeur x à chaque case et de placer la valeur maximal sur la fin
Author
Paul Brechenmacher
Date
(January 9th, 2024 9:22 PM)
Parameters
[in] a Arbre des chemins avec les cases accessibles
[in] maze Maze contenant la taille du labyrinthe
[in] x Valeur initialisé à 6
[in] tabAriane Tableau 2D initialisé
[out] x Valeur de x incrémenté ou non (accumulateur)
[out] tabAriane Tableau 2D modifié avec des valeurs de x incrementés sur les chemins
Definition at line 412 of file event.c.
{
     if(a->type == SPACE){
       (*tabAriane)[a->positions[0]][a->positions[1]] = *x;
       (*x)++;
     }else{
       (*tabAriane)[a->positions[0]][a->positions[1]] = maze.sizeMaze*maze.sizeMaze;
     }
     for(int n = 0; n < a->nbFils; n++){
         naviguerArbreChemins(a->fils[n],maze,tabAriane,x);
     }
 }
References node::fils, node::nbFils, node::positions, Maze::sizeMaze, SPACE, and node::type.
Referenced by filAriane2().
notSoRandom()
int notSoRandom (Jeu * jeu)
Modifie l'aléatoire pour une apparition des objets plus équilibrée.
Author
Etienne Massonnet
Date
(January 17th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant le niveau de la partie
[out] event entier correspondant à l'évènement choisi
Definition at line 264 of file event.c.
{
   int res;
   //chances de se produire pour les évènements :
   int health=1;
   int medikit=1;
   int damage=1;
   int fire=1;
   int drunk=1;
   int milk=1;
   int ariane=1;
   int poison=1;
   int score=1;
   int fun=1;
   int random = (rand()%10)+1;
   return res;
 }
remonterArbre()
void remonterArbre (arbreChemins a, int ** tabAriane, Jeu * jeu)
Permet de trouver le chemins le plus court (algo A*), en prenant toujours la plus petite valeur aux alentours.
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:27 AM)
Parameters
[in] tabAriane Arbre à l'arrivée du labyrinthe trouvé
[in] a Arbre à l'arrivée/la fin du labyrinthe
[in] jeu Jeu contenant le labyrinthe
[out] jeu Jeu contenant le labyrinthe avec le fil d'Ariane visible
Definition at line 444 of file event.c.
{
     if(tabAriane[a->positions[0]][a->positions[1]] != 6){
       int valMin = tabAriane[a->positions[0]][a->positions[1]];
       int idMin = 0;
       for(int n = 0; n < a->nbFils; n++){
         if(tabAriane[a->fils[n]->positions[0]][a->fils[n]->positions[1]]<valMin){
           valMin = tabAriane[a->fils[n]->positions[0]][a->fils[n]->positions[1]];
           idMin = n;
         }
       }
       if(tabAriane[a->parent->positions[0]][a->parent->positions[1]]<valMin){
         valMin = tabAriane[a->parent->positions[0]][a->parent->positions[1]];
         idMin = 4;
       }
       if(idMin == 4){
         if(jeu->maze.tabMaze[a->parent->positions[0]][a->parent->positions[1]] == SPACE){
             jeu->maze.tabMaze[a->parent->positions[0]][a->parent->positions[1]] = FIL;
         }
         remonterArbre(a->parent,tabAriane,jeu);
       }else{
          if(jeu->maze.tabMaze[a->fils[idMin]->positions[0]][a->fils[idMin]->positions[1]] == SPACE){
             jeu->maze.tabMaze[a->fils[idMin]->positions[0]][a->fils[idMin]->positions[1]] = FIL;
         }
         remonterArbre(a->fils[idMin],tabAriane,jeu);
       }
   }
 }
References FIL, node::fils, Jeu::maze, node::nbFils, node::parent, node::positions, SPACE, and Maze::tabMaze.
Referenced by filAriane2().
verifEtatEvent()
void verifEtatEvent (Joueur * j, int * typeEvent)
Vérifie l'état de l'évenement pour l'affichage et la fin du poison et du feu.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] j Pointeur du Joueur contenant les caractéristiques et les états du joueur
[in] typeEvent Type de l'event à effectuer et à vérifier
[out] j Joueur modifié avec un nouvel état (souvent le poison ou le feu)
Definition at line 374 of file event.c.
{
     // Afficher l'event en cours si pas NONE et si le joueur n'est pas en poison ou en feu
     if(*typeEvent != NONE && j->etatDangerJoueur == ETAT_NON_DANGER){
                 afficherUseItem(*typeEvent);
                 *typeEvent = NONE;
     }
     //Si le nombre de tours de poison et de feu est terminé
     if(j->etatTourRestants == 0){
         j->etatDangerJoueur = ETAT_NORMAL;
     }
 }
References afficherUseItem(), ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatTourRestants, and NONE.
Referenced by eventJoueur().
verifEvent()
void verifEvent (Jeu * jeu, int *** maze, int positionL, int positionC)
Vérifie si un event est placé sur la case demandé par le joueur et effectue un évenement aléatoirement.
Author
Paul Brechenmacher
Date
(January 12th, 2024 5:32 PM)
Parameters
[in] jeu Jeu contenant l'inventaire et les différentes options
[in] maze Pointeur du tableau 2D représentant le labyrinthe
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
Definition at line 282 of file event.c.
{
     if((*maze)[positionL][positionC] == EVENT){
         jeu->score = jeu->score + 25;
         int precEvent =-1;
         int randomEvent;
         usleep(5000);
         // pas remettre l'inversion clavier si on l'a pas enlevé avant
         do{
             randomEvent = (rand() % 10)+1; // entre random entre 1 et 10
         }while (precEvent==randomEvent);
         precEvent = randomEvent;
         //à remplacer par switch (notSoRandom(Jeu))
         switch (randomEvent) {
             case HEALTH:
                 healthPotionEvent(jeu);
                 break;
             case MEDIKIT:
                 medikitEvent(jeu);
                 break;
             case DAMAGE:
                 damageTrapEvent(jeu);
                 break;
             case FIRE:
                 jeu->j.etatDangerJoueur = ETAT_FEU;
                 jeu->j.etatTourRestants = jeu->j.etatTourRestants + (jeu->level/4)+1;
                break;
             case DRUNK:
                 jeu->j.etatSobreJoueur=ETAT_DRUNK;
                 if(jeu->options.typeMode == 4){
                     if(jeu->j.visionRange > 2){
                         jeu->j.visionRange--;
                     }
                 }
                 precEvent=1;
                 break;
             case MILK:
                 milkPotionEvent(jeu);
                 break;
             case ARIANE:
                 if(jeu->maze.typeMaze){
                     filAriane2(jeu);
                 }
                 break;
             case POISON:
                 jeu->j.etatDangerJoueur = ETAT_POISON;
                 jeu->j.etatTourRestants = jeu->j.etatTourRestants + (jeu->level/4)+2;
                 break;
             case SCORE:
                 jeu->score = jeu->score + 500;
                 break;
             case FUN:
                 if(jeu->options.typeEmoji == 1 && jeu->options.typeMode == 3){
                     system("clear");
                     lireArsenal();
                     sleep(5);
                     system("clear");
                 }else{
                     jeu->score = jeu->score + 250;
                     if(jeu->options.typeMode == 4){
                             jeu->j.visionRange++;
                     }
                 }
                 break;
             default:
                 printf("Error Event Switch Case\n");
                 break;
         }
         jeu->typeEvent = randomEvent;
     }
     if((*maze)[positionL][positionC] == KEY){
         jeu->j.findKeys = 1;
         jeu->score = jeu->score + 100;
     }
 }
References ARIANE, DAMAGE, damageTrapEvent(), DRUNK, ETAT_DRUNK, ETAT_FEU, ETAT_POISON, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, Joueur::etatTourRestants, EVENT, filAriane2(), Joueur::findKeys, FIRE, FUN, HEALTH, healthPotionEvent(), Jeu::j, KEY, Jeu::level, lireArsenal(), Jeu::maze, MEDIKIT, medikitEvent(), MILK, milkPotionEvent(), Jeu::options, POISON, SCORE, Jeu::score, Options::typeEmoji, Jeu::typeEvent, Maze::typeMaze, Options::typeMode, and Joueur::visionRange.
Referenced by deplacementMaze().
verifPoisonFeu()
void verifPoisonFeu (Joueur * j)
Permet d'effectuer les évenements poison et feu en influant sur la vie du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] j Joueur contenant sa vie et son nombre de tours restant avec EtatDanger != 0
[out] j Joueur avec vie modifié et nombre de tours restant modifié
Definition at line 359 of file event.c.
{
     if(j->etatDangerJoueur != ETAT_NON_DANGER){
             if(j->etatDangerJoueur == ETAT_POISON){
                 afficherUseItem(POISON);
                 j->pvHealth--;
                 j->etatTourRestants--;
             }
             if(j->etatDangerJoueur == ETAT_FEU){
                 j->pvHealth--;
                 afficherUseItem(FIRE);
                 j->etatTourRestants--;
             }
         }
 }
References afficherUseItem(), ETAT_FEU, ETAT_NON_DANGER, ETAT_POISON, Joueur::etatDangerJoueur, Joueur::etatTourRestants, FIRE, POISON, and Joueur::pvHealth.
Referenced by eventJoueur().
Variable Documentation
inversion
int inversion extern