Projet P2 : The Maze: game.h File Reference
game.h File Reference
#include "structure.h"
Functions
void initJeu (Jeu *jeu)
Permet d'initialiser le jeu.
void useItem (Jeu *jeu, int typeInput)
Permet d'utiliser un item dans son inventaire.
int deplacementValide (int positionL, int positionC, arbreChemins *a, Joueur j, int **maze, int taille)
Permet de valider si un déplacement est possible ou non.
void deplacementMaze (Jeu *jeu, arbreChemins *a, int ***maze, int positions[2])
Permet de vérifier et effectuer les bonnes fonctions selon les actions du joueur.
void gameOver (int level, int score, int highscore)
Affiche la fin de partie et sauvegarde le highscore dans un CSV.
void verifEvent (Jeu *jeu, int ***maze, int positionL, int positionC)
Vérifie si un event est placé sur la case demandé par le joueur et effectue un évenement aléatoirement.
void verifCheck (Jeu *jeu, int **maze, int positionL, int positionC)
Vérifie si la case demandée est un checkpoint.
void eventJoueur (int *typeEvent, Joueur *j)
Effectue l'event en vérifiant son type et l'état du joueur (souvent le poison ou le feu)
void ajouterItemInventaire (Jeu *jeu, int type, char *name)
Ajoute un objet dans l'inventaire du joueur.
int lenInt (int score)
Calcule la longueur d'un entier.
void getScoreCSV (Jeu *jeu)
Récupère dans le CSV le highscore le plus haut du joueur.
void saveHighScoreCSV (int highScore, int newscore)
Enregistre dans le CSV le highscore le plus haut du joueur.
void placerKeys (Maze *maze, Joueur *j)
Place les clefs dans les labyrinthes 3x3.
void jouerMaze (Jeu *jeu)
Permet de lancer la partie avec les options sélectionées et de jouer.
void verifPoisonFeu (Joueur *j)
Permet d'effectuer les évenements poison et feu en influant sur la vie du joueur.
void verifEtatEvent (Joueur *j, int *typeEvent)
Vérifie l'état de l'évenement pour l'affichage et la fin du poison et du feu.
void creerMegaMaze (Jeu *jeu)
Crée un labyrinthe 3x3 avec des checkpoints et des clefs.
void jouerJeu (Jeu *jeu)
Permet de lancher la partie avec un jeu initialisé
void playMegaMaze (Jeu *jeu)
Permet de jouer avec les labyrinthes 3x3.
void playMazeSimple (Jeu *jeu)
Permet de jouer avec le labyrinthe.
int getOptions (Options *options, int numOptions)
Récupère à chaque selon la ligne la valeur de l'option afin d'afficher la dernière selectionée.
void saveOptions (Options *options, int numOptions, int numId)
Permet de sauvegarder l'option selon la ligne et la valeur numId(choix du joueur pour une option)
void initOptions (char ****optionsTab, Options *options)
Permet d'initialiser et d'allouer les options et les tableaux du menu options
void freeGame (Jeu jeu)
void freeMaze (int **maze, int taille)
void freeArbre (arbreChemins arbre)
void afficherJoueur (int typeEmoji)
Affiche le joueur en fonction du type d'émoji.
void afficherAroundPlayer (int **matrice, int n, int typeEmoji, int typeMode, Joueur joueur, int visionRange)
Afficher le labyrinthe autour du joueur.
Function Documentation
afficherAroundPlayer()
void afficherAroundPlayer (int ** matrice, int n, int typeEmoji, int typeMode, Joueur joueur, int visionRange)
Afficher le labyrinthe autour du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] matrice Tableau 2D représentant le maze
[in] taille,typeEmoji,typeMode taille du maze, type d'émoji et type de mode
[in] joueur,visionRange joueur avec sa position et sa distance de vision
Definition at line 251 of file affichage.c.
{
     for(int l = joueur.positions[0]-visionRange;l < joueur.positions[0]+visionRange+1 ;l++){
         for(int c = joueur.positions[1]-visionRange; c < joueur.positions[1]+visionRange+1; c++){
            if(l < 0 || c < 0 || c >= n ||l >= n){
                 printf("  ");
            }else{
                 switch (matrice[l][c]) {
                 case SPACE:
                     printf("  "); // Espace vide
                     break;
                 case WALL:
                     printf("🧱"); // Mur
                     break;
                 case PLAYER:
                     afficherJoueur(typeEmoji);
                     break;
                 case END:
                     printf("🏁"); //Point d'arrivée
                     break;
                 case EVENT:
                     printf("❔");
                     break;
                 case KEY:
                     printf("🗝️ ");
                     break;
                 case CHECKPOINT:
                     printf("🚩");
                     break;
                 case FIL:
                     printf("🔹");
                     break;
                 default:
                     break;
             }
            }
         }
         printf("\n");
     }
 }
References afficherJoueur(), CHECKPOINT, END, EVENT, FIL, KEY, PLAYER, Joueur::positions, SPACE, and WALL.
Referenced by jouerMaze().
afficherJoueur()
afficherJoueur (int typeEmoji)
Affiche le joueur en fonction du type d'émoji.
Author
Paul Brechenmacher
Date
(January 9th, 2024 9:22 PM)
Parameters
[in] int typeEmoji
Definition at line 96 of file generation.c.
{
     switch (typeEmoji) {
         case 0:
             printf("👾"); // Joueur
             break;
         case 1:
             printf("🤡"); // Joueur
             break;
         case 2:
             printf("💎"); // Joueur
             break;
         case 3:
             printf("👽");
             break;
         case 4:
             printf("⚽");
             break;
     }
 }
Referenced by afficherAroundPlayer(), and afficherMatrice1().
ajouterItemInventaire()
void ajouterItemInventaire (Jeu * jeu, int type, char * name)
Ajoute un objet dans l'inventaire du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'inventaire
[in] type Type de l'objet à ajouter
[in] name Nom de l'objet à ajouter
[out] jeu Jeu contenant l'inventaire avec le nouvel item
Definition at line 213 of file event.c.
{
     int nbItems = 0;
     while(jeu->j.inventaire[nbItems].type != NONE){
         nbItems++;
     }
     jeu->j.inventaire[nbItems].type = type;
     jeu->j.inventaire[nbItems].name = name;
 }
References Joueur::inventaire, Jeu::j, Item::name, NONE, and Item::type.
Referenced by healthPotionEvent(), medikitEvent(), and milkPotionEvent().
creerMegaMaze()
creerMegaMaze (Jeu * jeu)
Crée un labyrinthe 3x3 avec des checkpoints et des clefs.
Author
Paul Brechenmacher
Date
(January 7th, 2024 2:11 PM)
Parameters
[in] jeu Jeu sans megaMaze(labyrinthe 3x3)
[out] jeu Jeu contenant un megaMaze avec des checkpoints et des clefs
Definition at line 483 of file generation.c.
{
     jeu->maze.sizeMaze = INITIALSIZE+(jeu->level);
     jeu->posMaze[0] = 1;
     jeu->posMaze[1] = 0;
     int size = 3;
     jeu->megamaze = (Maze**)malloc(size * sizeof(Maze*));
     for (int ligne = 0; ligne <  size; ligne++) {
         jeu->megamaze[ligne] = (Maze*)malloc(size * sizeof(Maze));
         for (int colonne= 0; colonne < size; colonne++) {
             mazeGenerator(&jeu->maze.tabMaze,jeu->maze.sizeMaze);
             mazePlacementComplexe(&jeu->maze.tabMaze,jeu->maze.sizeMaze,&jeu->j,ligne,colonne);
             jeu->maze.typeMaze = 0;
             jeu->megamaze[ligne][colonne] = jeu->maze;  // Initialiser la matrice avec des murs (-1)
         }
     }
 }
References INITIALSIZE, Jeu::j, Jeu::level, Jeu::maze, mazeGenerator(), mazePlacementComplexe(), Jeu::megamaze, Jeu::posMaze, Maze::sizeMaze, Maze::tabMaze, and Maze::typeMaze.
Referenced by playMegaMaze().
deplacementMaze()
void deplacementMaze (Jeu * jeu, arbreChemins * a, int *** maze, int positions[2])
Permet de vérifier et effectuer les bonnes fonctions selon les actions du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant toutes la position et le labyrinthe avec les actions du joueurs
[in] a Arbre contenant les cases accessibles pour le joueur
[in] maze Pointeur du tableau 2D représentant le labyrinthe
[in] positions Tableau des positions du joueur
[out] jeu Jeu contenant toutes la position et le labyrinthe mis à jour
Definition at line 96 of file game.c.
{
     switch (deplacementTouche(jeu->j.etatSobreJoueur)) {
                 case HAUT:
                     if(deplacementValide(positions[0]-1,positions[1],a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0]-1,positions[1]);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0]-1,positions[1]);
                             (*maze)[positions[0]-1][positions[1]] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[0]--;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case DROITE:
                     if(deplacementValide(positions[0],positions[1]+1,a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0],positions[1]+1);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0],positions[1]+1);
                             (*maze)[positions[0]][positions[1]+1] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[1]++;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case GAUCHE:
                     if(deplacementValide(positions[0],positions[1]-1,a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0],positions[1]-1);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0],positions[1]-1);
                             (*maze)[positions[0]][positions[1]-1] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[1]--;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case BAS:
                     if(deplacementValide(positions[0]+1,positions[1],a,jeu->j,*maze,jeu->maze.sizeMaze)){
                         verifCheck(jeu,*maze,positions[0]+1,positions[1]);
                         if(jeu->j.etatCheckPoint){
                             verifEvent(jeu,maze,positions[0]+1,positions[1]);
                             (*maze)[positions[0]+1][positions[1]] = PLAYER;
                             (*maze)[positions[0]][positions[1]] = SPACE;
                             if(jeu->j.etatCheckPoint == 2){
                                 (*maze)[positions[0]][positions[1]] = CHECKPOINT;
                                 jeu->j.etatCheckPoint = 1;
                             }
                             positions[0]++;
                         }else{
                             (*maze)[jeu->j.positions[0]][jeu->j.positions[1]] = PLAYER;
                             jeu->j.etatCheckPoint = 2;
                         }
                     }
                     break;
                 case HOTBAR1:
                     useItem(jeu,0);
                     break;
                 case HOTBAR2:
                     useItem(jeu,1);
                     break;
                 case HOTBAR3:
                     useItem(jeu,2);
                     break;
                 case HOTBAR4:
                     useItem(jeu,3);
                     break;
                 case HOTBAR5:
                     useItem(jeu,4);
                     break;
                 default:
                 printf("Invalid direction\n");
                     break;
             }
 }
References BAS, CHECKPOINT, deplacementTouche(), deplacementValide(), DROITE, Joueur::etatCheckPoint, Joueur::etatSobreJoueur, GAUCHE, HAUT, HOTBAR1, HOTBAR2, HOTBAR3, HOTBAR4, HOTBAR5, Jeu::j, Jeu::maze, PLAYER, Joueur::positions, Maze::sizeMaze, SPACE, useItem(), verifCheck(), and verifEvent().
Referenced by jouerMaze().
deplacementValide()
int deplacementValide (int positionL, int positionC, arbreChemins * a, Joueur j, int ** maze, int taille)
Permet de valider si un déplacement est possible ou non.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
[in] a Arbre contenant les cases accessibles pour le joueur
[in] j Jeu contenant la position du joueur
[in] maze Tableau 2D représentant le labyrinthe
[in] taille Taille du labyrinthe
Returns
0 si déplacement invalide / 1 si déplacement valide
Definition at line 70 of file game.c.
{
     int val = 0;
     if(positionL > -1 && positionC > -1 && positionC < taille && positionL < taille){
         if(maze[positionL][positionC] == END){
             if(!j.findKeys){
                 return 0;
             }
         }
     }
     for(int n = 0; n < (*a)->nbFils; n++){
         if((*a)->fils[n]->positions[0] == positionL && (*a)->fils[n]->positions[1] == positionC){
             *a = (*a)->fils[n];
             val = 1;
         }
     }
     if((*a)->parent->positions[0] == positionL && (*a)->parent->positions[1] == positionC){
             *a = (*a)->parent;
             val =  1;
         }
     return val;
 }
References END, node::fils, Joueur::findKeys, and node::parent.
Referenced by deplacementMaze().
eventJoueur()
void eventJoueur (int * typeEvent, Joueur * j)
Effectue l'event en vérifiant son type et l'état du joueur (souvent le poison ou le feu)
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] j Pointeur du Joueur contenant les caractéristiques et les états du joueur
[in] typeEvent Type de l'event à effectuer et à vérifier
[out] j Joueur modifié avec un nouvel état (souvent le poison ou le feu)
Definition at line 367 of file event.c.
{
     verifEtatEvent(j,typeEvent);
     verifPoisonFeu(j);
 }
References verifEtatEvent(), and verifPoisonFeu().
Referenced by jouerMaze().
freeArbre()
void freeArbre (arbreChemins arbre)
Definition at line 363 of file game.c.
{
     for(int n = 0; n < (arbre)->nbFils; n++){
         freeArbre((arbre)->fils[n]);
         free(arbre);
     }
 }
freeGame()
void freeGame (Jeu jeu)
Definition at line 378 of file game.c.
                       {
     // if (jeu.maze.typeMaze){
     //     for (int i = 0; i < jeu.maze.sizeMaze; i++) {
     //         for (int j = 0; j < jeu.maze.sizeMaze; j++) {
     //             printf("%d ", jeu.maze.tabMaze[i][j]);
     //         }
     //         printf("\n");
     //     }
     //     freeMaze(jeu.maze.tabMaze,jeu.maze.sizeMaze);
     //     }else{
     //         for(int i = 0; i < 3;i++){
     //             for(int j = 0; j < 3;j++){
     //             freeMaze(jeu.megamaze[i][j].tabMaze,jeu.megamaze[i][j].sizeMaze);
     //             }
     //         }
     //     }
     // freeArbre(jeu.maze.arbreChemin);
 }
Referenced by jouerJeu(), and main().
freeMaze()
void freeMaze (int ** maze, int taille)
Definition at line 370 of file game.c.
{
     for(int i = 0; i < taille;i++){
         free(maze[i]);
     }
     free(maze);
 }
gameOver()
void gameOver (int level, int score, int highScore)
Affiche la fin de partie et sauvegarde le highscore dans un CSV.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:59 PM)
Parameters
[in] level Niveau atteint par le joueur au cours de la partie
[in] score Score de la partie
[in] highscore Score le plus haut enregisté dans un CSV
Definition at line 244 of file game.c.
{
     system("clear");
     saveHighScoreCSV(highScore,score);
     afficherScore(level,score);
     printf("\e[1;92m""⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⡀⠀\n");
     printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣤⠀⠀⠀⢀⣴⣿⡶⠀⣾⣿⣿⡿⠟⠛⠁\n");
     printf("⠀⠀⠀⠀⠀⠀⣀⣀⣄⣀⠀⠀⠀⠀⣶⣶⣦⠀⠀⠀⠀⣼⣿⣿⡇⠀⣠⣿⣿⣿⠇⣸⣿⣿⣧⣤⠀⠀⠀\n");
     printf("⠀⠀⢀⣴⣾⣿⡿⠿⠿⠿⠇⠀⠀⣸⣿⣿⣿⡆⠀⠀⢰⣿⣿⣿⣷⣼⣿⣿⣿⡿⢀⣿⣿⡿⠟⠛⠁⠀⠀\n");
     printf("⠀⣴⣿⡿⠋⠁⠀⠀⠀⠀⠀⠀⢠⣿⣿⣹⣿⣿⣿⣿⣿⣿⡏⢻⣿⣿⢿⣿⣿⠃⣼⣿⣯⣤⣴⣶⣿⡤⠀\n");
     printf("⣼⣿⠏⠀⣀⣠⣤⣶⣾⣷⠄⣰⣿⣿⡿⠿⠻⣿⣯⣸⣿⡿⠀⠀⠀⠁⣾⣿⡏⢠⣿⣿⠿⠛⠋⠉⠀⠀⠀\n");
     printf("⣿⣿⠲⢿⣿⣿⣿⣿⡿⠋⢰⣿⣿⠋⠀⠀⠀⢻⣿⣿⣿⠇⠀⠀⠀⠀⠙⠛⠀⠀⠉⠁⠀⠀⠀⠀⠀⠀⠀\n");
     printf("⠹⢿⣷⣶⣿⣿⠿⠋⠀⠀⠈⠙⠃⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
     printf("⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣴⣶⣦⣤⡀⠀\n");
     printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⣠⡇⢰⣶⣶⣾⡿⠷⣿⣿⣿⡟⠛⣉⣿⣿⣿⠆\n");
     printf("⠀⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⡎⣿⣿⣦⠀⠀⠀⢀⣤⣾⠟⢀⣿⣿⡟⣁⠀⠀⣸⣿⣿⣤⣾⣿⡿⠛⠁⠀\n");
     printf("⠀⠀⠀⠀⣠⣾⣿⡿⠛⠉⢿⣦⠘⣿⣿⡆⠀⢠⣾⣿⠋⠀⣼⣿⣿⣿⠿⠷⢠⣿⣿⣿⠿⢻⣿⣧⠀⠀⠀\n");
     printf("⠀⠀⠀⣴⣿⣿⠋⠀⠀⠀⢸⣿⣇⢹⣿⣷⣰⣿⣿⠃⠀⢠⣿⣿⢃⣀⣤⣤⣾⣿⡟⠀⠀⠀⢻⣿⣆⠀⠀\n");
     printf("⠀⠀⠀⣿⣿⡇⠀⠀⢀⣴⣿⣿⡟⠀⣿⣿⣿⣿⠃⠀⠀⣾⣿⣿⡿⠿⠛⢛⣿⡟⠀⠀⠀⠀⠀⠻⠿⠀⠀\n");
     printf("⠀⠀⠀⠹⣿⣿⣶⣾⣿⣿⣿⠟⠁⠀⠸⢿⣿⠇⠀⠀⠀⠛⠛⠁⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
     printf("⠀⠀⠀⠀⠈⠙⠛⠛⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n""\e[0m");
     printf(BWHT"\n\n          Merci d'avoir joué !\n"reset);
     sleep(5);
 }
References afficherScore(), BWHT, reset, and saveHighScoreCSV().
Referenced by main().
getOptions()
int getOptions (Options * options, int numOptions)
Récupère à chaque selon la ligne la valeur de l'option afin d'afficher la dernière selectionée.
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:08 AM)
Parameters
[in] options Options enregistré
[in] numOptions Numéro de la ligne (0:skin / 1:mode / 2:niveau)
Returns
Type de l'ancien numId selon la ligne de l'option
Definition at line 348 of file game.c.
{
     switch (numOptions) {
         case 0:
             return options->typeEmoji;
         case 1:
             return options->typeMode;
         case 2:
             return options->typeLevel;
         default:
             return 0;
     }
 }
References Options::typeEmoji, Options::typeLevel, and Options::typeMode.
Referenced by optionChange().
getScoreCSV()
void getScoreCSV (Jeu * jeu)
Récupère dans le CSV le highscore le plus haut du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu avec le score le plus haut non initialisé
[out] jeu Jeu contenant le score le plus haut enregistré, 0 si le fichier n'existe pas
Definition at line 268 of file game.c.
{
     FILE* scoreFile = NULL;
     int highScore;
     char ligne[20];
     scoreFile = fopen("./out/score.csv", "r");
     if (scoreFile == NULL) {
         highScore = 0;
         printf("Erreur ouverture fichier \n");
     }else{
         highScore = atoi(fgets(ligne,20,scoreFile));
         fclose(scoreFile);
     }
     jeu->highScore = highScore;
 }
References Jeu::highScore.
Referenced by initJeu().
initJeu()
void initJeu (Jeu * jeu)
Permet d'initialiser le jeu.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'intégralité des variables non initialisées du jeu
[out] jeu Jeu initialisé
Definition at line 30 of file game.c.
                       {
     jeu->maze.typeMaze = 1;
     jeu->posMaze[0] = 1;
     jeu->posMaze[1] = 0;
     jeu->level = 0;
     jeu->score = 0;
     jeu->maze.sizeMaze = INITIALSIZE;
     modeHealth(&jeu->j.pvHealth,jeu->options.typeMode);
     jeu->j.findKeys = 1;
     jeu->j.etatCheckPoint = 1;
     jeu->typeEvent = NONE;
     jeu->j.inventaire = malloc(5*sizeof(Item)); //5 items max
     for(int nbItems = 0;nbItems < 5; nbItems++){
         jeu->j.inventaire[nbItems].type = NONE;
     }
     if(jeu->options.typeMode == 4){
         jeu->j.visionRange = 2;
     }
     jeu->maze.tabMaze = NULL;
     getScoreCSV(jeu);
     srand(time(NULL));
 }
References Joueur::etatCheckPoint, Joueur::findKeys, getScoreCSV(), INITIALSIZE, Joueur::inventaire, Jeu::j, Jeu::level, Jeu::maze, modeHealth(), NONE, Jeu::options, Jeu::posMaze, Joueur::pvHealth, Jeu::score, Maze::sizeMaze, Maze::tabMaze, Item::type, Jeu::typeEvent, Maze::typeMaze, Options::typeMode, and Joueur::visionRange.
Referenced by main().
initOptions()
void initOptions (char **** optionsTab, Options * options)
Permet d'initialiser et d'allouer les options et les tableaux du menu options
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:08 AM)
Parameters
[in] optionsTab Tableaux 2D menu options non alloués
[in] optionsTab Tableaux 2D menu options alloués et initialisés
[in] options Options non initialisées
[out] options Options initialisées par défaut
Definition at line 298 of file game.c.
{
     options->typeEmoji = 0;
     options->typeLevel = 1;
     options->typeMode = 0;
     (*optionsTab) = malloc(3*sizeof(char**));
     for (int i=0; i<3; i++){
         (*optionsTab)[i]=malloc(4*sizeof(char*));
         for (int j=0; j<5; j++){
         (*optionsTab)[i][j]=malloc(100*sizeof(char));
     }
     }
     (*optionsTab)[0][0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 👾 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 🤡 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 💎 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][3] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ 👽 ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[0][4] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BWHT"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣    "BWHT"◀ ⚽ ▶"BPUR"    ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║  "BWHT"◀ NORMAL ▶"BPUR"  ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║   "BWHT"◀ HARD ▶"BPUR"   ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║   "BWHT"◀ EASY ▶"BPUR"   ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][3] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║  "BWHT"◀ BONUS ▶"BPUR"   ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[1][4] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BWHT"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║  "BWHT"◀ PLAYER ▶"BPUR"  ║  ║  ════  ║\n║     ║  ║  ║  "BPUR"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║              ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][0] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 2 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][1] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 4 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][2] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 6 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][3] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║     "BWHT"◀ 8 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
     (*optionsTab)[2][4] = "╔═════╦═══════════════╦════════════════╗\n║  ║  ║  ═══╗  ════╗  ╚═══════  ══╦══  ║\n║  ╚══╩═══  ╠══════╩═══════╦══════╩══  ║\n║  ╔════════╣   "BPUR"< SKIN >"BPUR"   ╠════════╗  ║\n║  ║  ╔═════╣              ╠═══  ═══╝  ║\n║  ║  ╚══╗  ║   "BPUR"< MODE >"BPUR"   ║  ╔════════╣\n║  ╠══╗  ║  ║              ║  ║  ════  ║\n║     ║  ║  ║  "BWHT"< NIVEAU >"BPUR"  ║  ╚═════╗  ║\n╠══╣  ║  ║  ║    "BWHT"◀ 10 ▶"BPUR"    ║  ╔═════╝  ║\n║  ╚══╝  ║  ╚══════════════╝  ║  ║  ║  ║\n╚════════════════════════════════╩══╩══╝\n";
 }
References BPUR, BWHT, Options::typeEmoji, Options::typeLevel, and Options::typeMode.
Referenced by choixMenu().
jouerJeu()
void jouerJeu (Jeu * jeu)
Permet de lancher la partie avec un jeu initialisé
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu initialisé
[out] jeu Jeu terminé
Definition at line 221 of file game.c.
{
     while(jeu->j.pvHealth > 0){
         if((jeu->level/2)+1 >= ((jeu->options.typeLevel+1)*2)){ // niveau 1 2 3 4 5 6  7 / level  0 2 4 6 8 10 12  / typ 0 1 2 3 / lvl 3 5 7 9
             jeu->maze.typeMaze = 0; //
         }
         if (jeu->maze.typeMaze){
             playMazeSimple(jeu);
         }else{
             playMegaMaze(jeu);
         }
         if(jeu->j.pvHealth > 0){
             free(jeu->maze.tabMaze);
             free(jeu->maze.arbreChemin);
             jeu->level=jeu->level+2;
             jeu->score= jeu->score + (25*jeu->level);
         }
         freeGame(*jeu);
     }
 }
References Maze::arbreChemin, freeGame(), Jeu::j, Jeu::level, Jeu::maze, Jeu::options, playMazeSimple(), playMegaMaze(), Joueur::pvHealth, Jeu::score, Maze::tabMaze, Options::typeLevel, and Maze::typeMaze.
Referenced by main().
jouerMaze()
void jouerMaze (Jeu * jeu)
Permet de lancer la partie avec les options sélectionées et de jouer.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] jeu Jeu avec le maze avant déplacement joueur
[out] jeu Jeu après le déplacement joueur
Definition at line 56 of file game.c.
{
     system("clear");
     afficherScore(jeu->level,jeu->score);
     if(jeu->options.typeMode == 4){
         afficherAroundPlayer(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode,jeu->j,jeu->j.visionRange);
     }else{
         afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
     }
     afficherInventaire(*jeu);
     eventJoueur(&jeu->typeEvent,&jeu->j);
     deplacementMaze(jeu,&jeu->maze.arbreChemin,&jeu->maze.tabMaze,jeu->j.positions);
 }
References afficherAroundPlayer(), afficherInventaire(), afficherMatrice1(), afficherScore(), Maze::arbreChemin, deplacementMaze(), eventJoueur(), Jeu::j, Jeu::level, Jeu::maze, Jeu::options, Joueur::positions, Jeu::score, Maze::sizeMaze, Maze::tabMaze, Options::typeEmoji, Jeu::typeEvent, Options::typeMode, and Joueur::visionRange.
Referenced by playMazeSimple(), and playMegaMaze().
lenInt()
int lenInt (int score)
Calcule la longueur d'un entier.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] score Score du joueur
Returns
Longeur de l'entier
Definition at line 203 of file affichage.c.
                      {
     int len = 0;
     if (score == 0){
         len = 1;
     }
     while(score != 0){
         score = score/10;
         len++;
     }
     return len;
 }
Referenced by afficherScore().
placerKeys()
placerKeys (Maze * maze, Joueur * j)
Place les clefs dans les labyrinthes 3x3.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:29 PM)
Parameters
[in] maze Maze contenant le labyrinthe, son type et sa taille
[in] j Joueur initialisé avec 0 clé trouvée
[out] maze Maze contenant le labyrinthe avec la clé placée
Definition at line 526 of file generation.c.
{
         j->findKeys = 0;
         int lrandom = rand() % maze->sizeMaze;
         int crandom = rand() % maze->sizeMaze;
         do{
             lrandom = rand() % maze->sizeMaze;
             crandom = rand() % maze->sizeMaze;
         }while(maze->tabMaze[lrandom][crandom] != SPACE);
             maze->tabMaze[lrandom][crandom] = KEY;
 }
References Joueur::findKeys, KEY, Maze::sizeMaze, SPACE, and Maze::tabMaze.
Referenced by playMegaMaze().
playMazeSimple()
void playMazeSimple (Jeu * jeu)
Permet de jouer avec le labyrinthe.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:59 PM)
Parameters
[in] jeu Jeu avec maze, arbreChemins et events créés/placés
[out] jeu Jeu avec maze, arbreChemins modifiés
Definition at line 197 of file game.c.
{
     creerMaze(jeu);
     //mazeCSV(&jeu->maze);
     placerEvents(&jeu->maze,jeu->level);
     while(jeu->maze.arbreChemin->type && jeu->j.pvHealth > 0){
         jouerMaze(jeu);
     }
 }
References Maze::arbreChemin, creerMaze(), Jeu::j, jouerMaze(), Jeu::level, Jeu::maze, placerEvents(), Joueur::pvHealth, and node::type.
Referenced by jouerJeu().
playMegaMaze()
void playMegaMaze (Jeu * jeu)
Permet de jouer avec les labyrinthes 3x3.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:59 PM)
Parameters
[in] jeu Jeu avec maze, arbreChemins et events clefs créés/placés
[out] jeu Jeu avec maze, arbreChemins modifiés
Definition at line 205 of file game.c.
{
     creerMegaMaze(jeu);
     jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]];
     jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
     for(int i = 0; i < 3 ;i++){
         for(int j = 0; j < 3;j++){
             placerEvents(&jeu->megamaze[i][j],jeu->level/2);
             //mazebigCSV(&jeu->megamaze[i][j],i,j);
             }
         }
     placerKeys(&jeu->megamaze[rand() % 3][rand() % 3],&jeu->j);
     while((!jeu->j.findKeys || jeu->maze.arbreChemin->type) && jeu->j.pvHealth > 0){
         jouerMaze(jeu);
     }
 }
References Maze::arbreChemin, creerArbreChemins(), creerMegaMaze(), Joueur::findKeys, Jeu::j, jouerMaze(), Jeu::level, Jeu::maze, Jeu::megamaze, placerEvents(), placerKeys(), Joueur::positions, Jeu::posMaze, Joueur::pvHealth, Maze::sizeMaze, Maze::tabMaze, and node::type.
Referenced by jouerJeu().
saveHighScoreCSV()
void saveHighScoreCSV (int highScore, int score)
Enregistre dans le CSV le highscore le plus haut du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] highScore Plus haut score réalisé par le joueur
[in] newscore Score de la partie actuelle
Definition at line 283 of file game.c.
{
     FILE* scoreFile = NULL;
     scoreFile = fopen("./out/score.csv", "w");
     if (scoreFile == NULL) {
         printf("Erreur ouverture fichier \n");
     }else{
         if(score > highScore){
             fprintf(scoreFile,"%d",score);
         }else{
             fprintf(scoreFile,"%d",highScore);
         }
         fclose(scoreFile);
     }
 }
Referenced by gameOver().
saveOptions()
void saveOptions (Options * options, int numOptions, int numId)
Permet de sauvegarder l'option selon la ligne et la valeur numId(choix du joueur pour une option)
Author
Paul Brechenmacher
Date
(January 9th, 2024 1:08 AM)
Parameters
[in] options Options enregistré
[in] numOptions Numéro de la ligne (0:skin / 1:mode / 2:niveau)
[in] numId Numéro du type voulu pour l'option (ex emoji : 0 : 👾)
[out] options Options modifié
Definition at line 334 of file game.c.
{
     switch (numOptions) {
         case 0:
             options->typeEmoji = numId;
             break;
         case 1:
             options->typeMode = numId;
             break;
         case 2:
             options->typeLevel = numId;
             break;
     }
 }
References Options::typeEmoji, Options::typeLevel, and Options::typeMode.
Referenced by optionChange().
useItem()
void useItem (Jeu * jeu, int typeInput)
Permet d'utiliser un item dans son inventaire.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] typeInput Numéro de la touche appuyée pour utiliser un objet
[in] jeu Jeu avec inventaire avec l'item utilisé
[out] jeu Jeu avec inventaire sans l'item utilisé
Definition at line 372 of file event.c.
{
     switch (jeu->j.inventaire[typeInput].type){
         case HEALTH:
             jeu->j.pvHealth = jeu->j.pvHealth +2;
             break;
         case MEDIKIT:
             jeu->j.pvHealth = jeu->j.pvHealth +5;
             break;
         case MILK:
             if(jeu->j.etatSobreJoueur && jeu->options.typeMode == 4){
                 jeu->j.visionRange++;
             }
             jeu->j.etatSobreJoueur = ETAT_NORMAL;
             jeu->j.etatDangerJoueur = ETAT_NON_DANGER;
             break;
         default:
             break;
     }
     jeu->j.inventaire[typeInput].type = NONE;
 }
References ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, HEALTH, Joueur::inventaire, Jeu::j, MEDIKIT, MILK, NONE, Jeu::options, Joueur::pvHealth, Item::type, Options::typeMode, and Joueur::visionRange.
Referenced by deplacementMaze().
verifCheck()
verifCheck (Jeu * jeu, int ** maze, int positionL, int positionsC)
Vérifie si la case demandée est un checkpoint.
Author
Paul Brechenmacher
Date
(January 12th, 2024 5:32 PM)
Parameters
[in] jeu Jeu contenant l'inventaire et les différentes options
[in] maze Tableau 2D représentant le labyrinthe
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
Definition at line 557 of file generation.c.
{
     if(positionL > -1 && positionC > -1 && positionC < jeu->maze.sizeMaze && positionL < jeu->maze.sizeMaze){
         if((maze[positionL][positionC]) == CHECKPOINT){
             jeu->j.etatCheckPoint = 0;
             jeu->maze.tabMaze[jeu->j.positions[0]][jeu->j.positions[1]] = SPACE;
             if(positionC == 0){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]-1];
                 jeu->posMaze[1]--;
                 findCheck(jeu,jeu->maze.sizeMaze-1,1);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionL == 0){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]-1][jeu->posMaze[1]];
                 jeu->posMaze[0]--;
                 findCheck(jeu,jeu->maze.sizeMaze-1,0);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionC == (jeu->maze.sizeMaze-1)){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]+1];
                 jeu->posMaze[1]++;
                 afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
                 findCheck(jeu,0,1);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionL == (jeu->maze.sizeMaze-1)){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]+1][jeu->posMaze[1]];
                 jeu->posMaze[0]++;
                 findCheck(jeu,0,0);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
         }
     }
 }
References afficherMatrice1(), Maze::arbreChemin, CHECKPOINT, creerArbreChemins(), Joueur::etatCheckPoint, findCheck(), Jeu::j, Jeu::maze, Jeu::megamaze, Jeu::options, Joueur::positions, Jeu::posMaze, Maze::sizeMaze, SPACE, Maze::tabMaze, Options::typeEmoji, and Options::typeMode.
Referenced by deplacementMaze().
verifEtatEvent()
void verifEtatEvent (Joueur * j, int * typeEvent)
Vérifie l'état de l'évenement pour l'affichage et la fin du poison et du feu.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] j Pointeur du Joueur contenant les caractéristiques et les états du joueur
[in] typeEvent Type de l'event à effectuer et à vérifier
[out] j Joueur modifié avec un nouvel état (souvent le poison ou le feu)
Definition at line 355 of file event.c.
{
     // Afficher l'event en cours si pas NONE et si le joueur n'est pas en poison ou en feu
     if(*typeEvent != NONE && j->etatDangerJoueur == ETAT_NON_DANGER){
                 afficherUseItem(*typeEvent);
                 *typeEvent = NONE;
     }
     //Si le nombre de tours de poison et de feu est terminé
     if(j->etatTourRestants == 0){
         j->etatDangerJoueur = ETAT_NORMAL;
     }
 }
References afficherUseItem(), ETAT_NON_DANGER, ETAT_NORMAL, Joueur::etatDangerJoueur, Joueur::etatTourRestants, and NONE.
Referenced by eventJoueur().
verifEvent()
void verifEvent (Jeu * jeu, int *** maze, int positionL, int positionC)
Vérifie si un event est placé sur la case demandé par le joueur et effectue un évenement aléatoirement.
Author
Paul Brechenmacher
Date
(January 12th, 2024 5:32 PM)
Parameters
[in] jeu Jeu contenant l'inventaire et les différentes options
[in] maze Pointeur du tableau 2D représentant le labyrinthe
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
Definition at line 263 of file event.c.
{
     if((*maze)[positionL][positionC] == EVENT){
         jeu->score = jeu->score + 25;
         int precEvent =-1;
         int randomEvent;
         usleep(5000);
         // pas remettre l'inversion clavier si on l'a pas enlevé avant
         do{
             randomEvent = (rand() % 10)+1; // entre random entre 1 et 10
         }while (precEvent==randomEvent);
         precEvent = randomEvent;
         switch (randomEvent) {
             case HEALTH:
                 healthPotionEvent(jeu);
                 break;
             case MEDIKIT:
                 medikitEvent(jeu);
                 break;
             case DAMAGE:
                 damageTrapEvent(jeu);
                 break;
             case FIRE:
                 jeu->j.etatDangerJoueur = ETAT_FEU;
                 jeu->j.etatTourRestants = jeu->j.etatTourRestants + (jeu->level/4)+1;
                break;
             case DRUNK:
                 jeu->j.etatSobreJoueur=ETAT_DRUNK;
                 if(jeu->options.typeMode == 4){
                     if(jeu->j.visionRange > 2){
                         jeu->j.visionRange--;
                     }
                 }
                 precEvent=1;
                 break;
             case MILK:
                 milkPotionEvent(jeu);
                 break;
             case ARIANE:
                 if(jeu->maze.typeMaze){
                     filAriane2(jeu);
                 }
                 break;
             case POISON:
                 jeu->j.etatDangerJoueur = ETAT_POISON;
                 jeu->j.etatTourRestants = jeu->j.etatTourRestants + (jeu->level/4)+2;
                 break;
             case SCORE:
                 jeu->score = jeu->score + 500;
                 break;
             case FUN:
                 if(jeu->options.typeEmoji == 1 && jeu->options.typeMode == 3){
                     system("clear");
                     lireArsenal();
                     sleep(5);
                     system("clear");
                 }else{
                     jeu->score = jeu->score + 250;
                     if(jeu->options.typeMode == 4){
                             jeu->j.visionRange++;
                     }
                 }
                 break;
             default:
                 printf("Error Event Switch Case\n");
                 break;
         }
         jeu->typeEvent = randomEvent;
     }
     if((*maze)[positionL][positionC] == KEY){
         jeu->j.findKeys = 1;
         jeu->score = jeu->score + 100;
     }
 }
References ARIANE, DAMAGE, damageTrapEvent(), DRUNK, ETAT_DRUNK, ETAT_FEU, ETAT_POISON, Joueur::etatDangerJoueur, Joueur::etatSobreJoueur, Joueur::etatTourRestants, EVENT, filAriane2(), Joueur::findKeys, FIRE, FUN, HEALTH, healthPotionEvent(), Jeu::j, KEY, Jeu::level, lireArsenal(), Jeu::maze, MEDIKIT, medikitEvent(), MILK, milkPotionEvent(), Jeu::options, POISON, SCORE, Jeu::score, Options::typeEmoji, Jeu::typeEvent, Maze::typeMaze, Options::typeMode, and Joueur::visionRange.
Referenced by deplacementMaze().
verifPoisonFeu()
void verifPoisonFeu (Joueur * j)
Permet d'effectuer les évenements poison et feu en influant sur la vie du joueur.
Author
Paul Brechenmacher
Date
(January 7th, 2024 11:12 AM)
Parameters
[in] j Joueur contenant sa vie et son nombre de tours restant avec EtatDanger != 0
[out] j Joueur avec vie modifié et nombre de tours restant modifié
Definition at line 340 of file event.c.
{
     if(j->etatDangerJoueur != ETAT_NON_DANGER){
             if(j->etatDangerJoueur == ETAT_POISON){
                 afficherUseItem(POISON);
                 j->pvHealth--;
                 j->etatTourRestants--;
             }
             if(j->etatDangerJoueur == ETAT_FEU){
                 j->pvHealth--;
                 afficherUseItem(FIRE);
                 j->etatTourRestants--;
             }
         }
 }
References afficherUseItem(), ETAT_FEU, ETAT_NON_DANGER, ETAT_POISON, Joueur::etatDangerJoueur, Joueur::etatTourRestants, FIRE, POISON, and Joueur::pvHealth.
Referenced by eventJoueur().