Projet P2 : The Maze: generation.c File Reference
generation.c File Reference
#include "generation.h"
Functions
void setStart (int ***maze, int taille, int randPlacement, Joueur *j)
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
void setEnd (int ***maze, int taille, int randPlacement)
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
void afficherJoueur (int typeEmoji)
Affiche le joueur en fonction du type d'émoji.
void afficherMatrice1 (int **matrice, int n, int typeEmoji, int typeMode)
Afficher le labyrinthe.
void allouerTab1 (int **tab, int taille)
Alloue les tableaux 1D.
void allouerTab2 (int ***tab, int taille)
Alloue les tableaux 2D.
void mazeGenerator (int ***maze, int taille)
void setValues (int values[4][19], int ligne, int colonne, int taille)
void ajouter_pile (const int ligne, const int colonne, int **cStack, int **rStack, int *index)
Permet d'ajouter dans la pile la case visitée.
void retirer_pile (const int ligne, const int colonne, int **cStack, int **rStack, int *index)
Permet de retirer dans la pile une case visitée pour revenir sur des cases disponibles (Randomized depth-first search)
arbreChemins creerArbreChemins (arbreChemins a, int positionL, int positionC, int **maze, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe.
arbreChemins creerArbreCheminsCache (arbreChemins a, int positionL, int positionC, int **maze, arbreChemins a_parent, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe avec son parent et ses fils.
void mazePlacementSimple (int ***maze, int taille, Joueur *j)
void setCheck (int ***maze, int taille, int randPlacement)
void mazePlacementComplexe (int ***maze, int taille, Joueur *j, int posMazeL, int posMazeC)
void creerMegaMaze (Jeu *jeu)
Crée un labyrinthe 3x3 avec des checkpoints et des clefs.
void creerMaze (Jeu *jeu)
Permet de générer le labyrinthe avec la méthode Randomized depth-first search.
void placerEvents (Maze *maze, int level)
Permet de placer les events de manières aléatoire dans le labyrythne.
void placerKeys (Maze *maze, Joueur *j)
Place les clefs dans les labyrinthes 3x3.
void findCheck (Jeu *jeu, int positionInverse, int mode)
void verifCheck (Jeu *jeu, int **maze, int positionL, int positionC)
Vérifie si la case demandée est un checkpoint.
Function Documentation
afficherJoueur()
void afficherJoueur (int typeEmoji)
Affiche le joueur en fonction du type d'émoji.
Author
Paul Brechenmacher
Date
(January 9th, 2024 9:22 PM)
Parameters
[in] int typeEmoji
Definition at line 96 of file generation.c.
{
     switch (typeEmoji) {
         case 0:
             printf("👾"); // Joueur
             break;
         case 1:
             printf("🤡"); // Joueur
             break;
         case 2:
             printf("💎"); // Joueur
             break;
         case 3:
             printf("👽");
             break;
         case 4:
             printf("⚽");
             break;
     }
 }
Referenced by afficherAroundPlayer(), and afficherMatrice1().
afficherMatrice1()
afficherMatrice1 (int ** matrice, int taille, int typeEmoji, int typeMode)
Afficher le labyrinthe.
Author
Gabin Alquier
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] matrice Tableau 2D représentant le maze
[in] taille,typeEmoji,typeMode taille du maze, type d'émoji et type de mode
Definition at line 117 of file generation.c.
{
    // Afficher la matrice avec des symboles correspondant aux éléments
    for(int i = 0; i < n; i++){
         for(int j =0; j < n; j++){
             switch (matrice[i][j]) {
                 case SPACE:
                     printf("  "); // Espace vide
                     break;
                 case WALL:
                     if(typeMode != 3){
                         printf("🧱"); // Mur
                     }else{
                         printf("  "); //Mur invisible
                     }
                     break;
                 case PLAYER:
                     afficherJoueur(typeEmoji);
                     break;
                 case END:
                     printf("🏁"); //Point d'arrivée
                     break;
                 case EVENT:
                     printf("❔");
                     break;
                 case KEY:
                     printf("🗝️ ");
                     break;
                 case CHECKPOINT:
                     printf("🚩");
                     break;
                 case FIL:
                     printf("🔹");
                     break;
                 case WHITE:
                     printf("⬜");
                     break;
                 case BLUE:
                     printf("🟦");
                     break;
                 default:
                     break;
             }
         }
         printf("\n");
     }
 }
References afficherJoueur(), BLUE, CHECKPOINT, END, EVENT, FIL, KEY, PLAYER, SPACE, WALL, and WHITE.
Referenced by findCheck(), jouerMaze(), and verifCheck().
ajouter_pile()
ajouter_pile (const int colonne, const int ligne, int ** cStack, int ** rStack, int * index)
Permet d'ajouter dans la pile la case visitée.
Author
Paul Brechenmacher / Gabin Alquier
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] colonne Colonne actuelle
[in] ligne Ligne actuelle
[in] cStack Pointeur de la pile colonne
[in] rStack Pointeur de la pile ligne
[in] index Pointeur de l'index actuel dans le nombre de cases visitées
[out] rStack Pile colonne modifié nouvelle case visitée
[out] cStack Pile colonne modifié nouvelle case visitée
Definition at line 279 of file generation.c.
{
     // Ajouter la position actuelle à la pil
     (*cStack)[ *index ] = ligne;
     (*rStack)[ *index ] = colonne;
     *index += 1;
 }
Referenced by mazeGenerator().
allouerTab1()
allouerTab1 (int ** tab, int taille)
Alloue les tableaux 1D.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] tab Pointeur Tableau 1D non alloué
[in] taille Taille du tableau 1D
[out] tab Tableau 1D alloué
Definition at line 165 of file generation.c.
{
     int n = (taille*taille);
     *tab = (int*)malloc(n * sizeof(int));
     for (int i= 0; i < n; i++) {
         (*tab)[i] = 0;  // Initialiser la matrice avec des murs (-1)
         }
     }
Referenced by mazeGenerator().
allouerTab2()
allouerTab2 (int *** tab, int taille)
Alloue les tableaux 2D.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] tab Pointeur Tableau 2D non alloué
[in] taille Taille du tableau 2D
[out] tab Tableau 2D alloué
Definition at line 174 of file generation.c.
{
     *tab = (int**)malloc(taille * sizeof(int*));
     for (int ligne = 0; ligne < taille; ligne++) {
         (*tab)[ligne] = (int*)malloc(taille * sizeof(int));
         for (int colonne= 0; colonne < taille; colonne++) {
             (*tab)[ligne][colonne] = WALL;  // Initialiser la matrice avec des murs (-1)
         }
     }
 }
References WALL.
Referenced by filAriane2(), lireArsenal(), and mazeGenerator().
creerArbreChemins()
creerArbreChemins (arbreChemins a, int positionL, int positionC, int ** maze, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] positionL Position de la ligne de la case dans le labyrinthe à rajouter dans l'arbre
[in] positionC Position de la colonne de la case dans le labyrinthe à rajouter dans l'arbre
[in] a Arbre avec les chemins possibles
[in] maze Tableau contentant le labyrinthe
[in] taille Taille du labyrinthe
Returns
Arbre avec une nouvelle case accessible dans le labyrinthe
Definition at line 294 of file generation.c.
{
     arbreChemins a_parent;
     a_parent = malloc(sizeof(node));
     a_parent->nbFils = 1;
     a_parent->positions[0] = positionL;
     a_parent->positions[1] = positionC;
     return creerArbreCheminsCache(a,positionL,positionC,maze,a_parent,taille);
 }
References creerArbreCheminsCache(), node::nbFils, and node::positions.
Referenced by creerMaze(), playMegaMaze(), and verifCheck().
creerArbreCheminsCache()
creerArbreCheminsCache (arbreChemins a, int positionL, int positionC, int ** maze, arbreChemins a_parent, int taille)
Permet de manière récursive de créer un arbre des cases accessibles dans le labyrinthe avec son parent et ses fils.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] positionL Position de la ligne de la case dans le labyrinthe à rajouter dans l'arbre
[in] positionC Position de la colonne de la case dans le labyrinthe à rajouter dans l'arbre
[in] a Arbre avec les chemins possibles
[in] maze Tableau contentant le labyrinthe
[in] a_parent Arbre parent permettant au joueur de revenir sur ses pas
[in] taille Taille du labyrinthe
Returns
Arbre avec une nouvelle case accessible dans le labyrinthe
Definition at line 304 of file generation.c.
{
         a = malloc(sizeof(node));
         a->fils = malloc(1 * sizeof(node*));
         a->positions[0] = positionL;
         a->positions[1] = positionC;
         a->parent = a_parent;
         a->nbFils = 0;
         //afficherMatrice(maze, SIZE);
         if(maze[a->positions[0]][a->positions[1]] == END){
             a->type = 0;
         }else{
             if(maze[a->positions[0]][a->positions[1]] == CHECKPOINT){
                 a->type = 2;
             }else{
                 a->type = 1;
             }
         }
         if(positionC != taille-1){
             if(maze[a->positions[0]][a->positions[1]+1] >= SPACE && (a->positions[0] != a->parent->positions[0] || a->positions[1]+1 != a->parent->positions[1])){ //DROITE
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL, positionC+1,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
             }
         }
         if(positionL != taille-1){
             if(maze[a->positions[0]+1][a->positions[1]] >= SPACE && (a->positions[0]+1 != a->parent->positions[0] || a->positions[1] != a->parent->positions[1])){ // BAS
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL+1, positionC,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
             }
         }
         if(positionL != 0){
             if(maze[a->positions[0]-1][a->positions[1]] >= SPACE && (a->positions[0]-1 != a->parent->positions[0] || a->positions[1] != a->parent->positions[1])){ //HAUT
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL-1, positionC,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
             }
         }
         if(positionC != 0){
             if(maze[a->positions[0]][a->positions[1]-1] >= SPACE && (a->positions[0] != a->parent->positions[0] || a->positions[1]-1 != a->parent->positions[1])){ //GAUCHE
                 a->fils[a->nbFils] = creerArbreCheminsCache(a->fils[a->nbFils],positionL, positionC-1,maze,a,taille);
                 a->fils = realloc(a->fils,(a->nbFils+1) * sizeof(node*));
                 a->nbFils++;
                 return a;
             }
             return a;
         }
         return a;
     }
References CHECKPOINT, END, node::fils, node::nbFils, node::parent, node::positions, SPACE, and node::type.
Referenced by creerArbreChemins().
creerMaze()
creerMaze (Jeu * jeu)
Permet de générer le labyrinthe avec la méthode Randomized depth-first search.
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
Author
Paul Brechenmacher / Gabin Alquier
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] maze Jeu contenant l'intégralité des variables du jeu
[in] taille Jeu contenant l'intégralité des variables du jeu
[out] maze Jeu contenant le labyrinthe et l'arbre des chemins
Author
Paul Brechenmacher / Gabin Alquier
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] jeu Jeu contenant l'intégralité des variables du jeu
[out] jeu Jeu contenant le labyrinthe et l'arbre des chemins
Definition at line 502 of file generation.c.
{
     jeu->maze.sizeMaze = jeu->maze.sizeMaze + jeu->level;
     mazeGenerator(&jeu->maze.tabMaze,jeu->maze.sizeMaze);
     mazePlacementSimple(&jeu->maze.tabMaze,jeu->maze.sizeMaze,&jeu->j);
     jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
     if(jeu->maze.typeMaze){
         jeu->maze.arbreCheminDepart = jeu->maze.arbreChemin;
         }
 }
References Maze::arbreChemin, Maze::arbreCheminDepart, creerArbreChemins(), Jeu::j, Jeu::level, Jeu::maze, mazeGenerator(), mazePlacementSimple(), Joueur::positions, Maze::sizeMaze, Maze::tabMaze, and Maze::typeMaze.
Referenced by playMazeSimple().
creerMegaMaze()
void creerMegaMaze (Jeu * jeu)
Crée un labyrinthe 3x3 avec des checkpoints et des clefs.
Author
Paul Brechenmacher
Date
(January 7th, 2024 2:11 PM)
Parameters
[in] jeu Jeu sans megaMaze(labyrinthe 3x3)
[out] jeu Jeu contenant un megaMaze avec des checkpoints et des clefs
Definition at line 483 of file generation.c.
{
     jeu->maze.sizeMaze = INITIALSIZE+(jeu->level);
     jeu->posMaze[0] = 1;
     jeu->posMaze[1] = 0;
     int size = 3;
     jeu->megamaze = (Maze**)malloc(size * sizeof(Maze*));
     for (int ligne = 0; ligne <  size; ligne++) {
         jeu->megamaze[ligne] = (Maze*)malloc(size * sizeof(Maze));
         for (int colonne= 0; colonne < size; colonne++) {
             mazeGenerator(&jeu->maze.tabMaze,jeu->maze.sizeMaze);
             mazePlacementComplexe(&jeu->maze.tabMaze,jeu->maze.sizeMaze,&jeu->j,ligne,colonne);
             jeu->maze.typeMaze = 0;
             jeu->megamaze[ligne][colonne] = jeu->maze;  // Initialiser la matrice avec des murs (-1)
         }
     }
 }
References INITIALSIZE, Jeu::j, Jeu::level, Jeu::maze, mazeGenerator(), mazePlacementComplexe(), Jeu::megamaze, Jeu::posMaze, Maze::sizeMaze, Maze::tabMaze, and Maze::typeMaze.
Referenced by playMegaMaze().
findCheck()
void findCheck (Jeu * jeu, int positionInverse, int mode)
Definition at line 538 of file generation.c.
{
     int i = 1;
     // mode 1 --> recherche ligne sinon  0 --> recherche colonne
     afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
     if(mode){
         while(jeu->maze.tabMaze[i][positionInverse] != CHECKPOINT && i < jeu->maze.sizeMaze){
             i++;
         }
         jeu->j.positions[0] = i;
         jeu->j.positions[1] = positionInverse;
     }else{
         while(jeu->maze.tabMaze[positionInverse][i] != CHECKPOINT && i < jeu->maze.sizeMaze){
             i++;
         }
         jeu->j.positions[0] = positionInverse;
         jeu->j.positions[1] = i;
     }
 }
References afficherMatrice1(), CHECKPOINT, Jeu::j, Jeu::maze, Jeu::options, Joueur::positions, Maze::sizeMaze, Maze::tabMaze, Options::typeEmoji, and Options::typeMode.
Referenced by verifCheck().
mazeGenerator()
void mazeGenerator (int *** maze, int taille)
Definition at line 184 of file generation.c.
{
     int ligne;
     int colonne;
     int index = 0;
     int *indexPtr = &index;
     int* cStack = NULL;
     int* rStack = NULL;
     int direction;
     int cont = 4;
     int maze_dir[ 4 ] = { 0 };
     int values[ DIR ][ VALUES ] = { 0 };
     int x;
     int set = 0;
     allouerTab1(&cStack, taille);
     allouerTab1(&rStack, taille);
     allouerTab2(maze,taille);
     ligne = 3;
     colonne = 5;
     (*maze)[ ligne ][ colonne ] = 1;
     ajouter_pile( ligne, colonne, &cStack, &rStack, indexPtr );
     srand( time( NULL ) );
     while(index >= 1) {
         while(cont != 0) {
             while( cont > 0 ) {
                 set = 0;
                 direction = ( 1 + rand() % DIR ) - 1;
                 if ( maze_dir[ direction ] == 0 ) {
                     maze_dir[ direction ] = 1;
                     cont--;
                     setValues( values, ligne, colonne,taille);
                     for ( x = 0; x < DIR; ++x ) {
                         if ( direction == x && (*maze)[values[x][0]][values[x][1]] !=SPACE && (*maze)[values[x][2]][values[x][3]] !=SPACE && (*maze)[values[x][4]][values[x][5]] !=SPACE && (*maze)[values[x][6]][values[x][7]] !=SPACE && (*maze)[values[x][8]][values[x][9]] !=SPACE && (*maze)[values[x][10]][values[x][11]] !=SPACE && (*maze)[values[x][12]][values[x][13]] !=SPACE && (*maze)[values[x][14]][values[x][15]] !=SPACE && (*maze)[values[x][16]][values[x][17]] !=SPACE && values[x][18] ) {
                             ligne = values[ x ][ 0 ];
                             colonne = values[ x ][ 1 ];
                             (*maze)[ ligne ][ colonne ] = SPACE;
                             setValues( values, ligne, colonne,taille);
                             ligne = values[ x ][ 0 ];
                             colonne = values[ x ][ 1 ];
                             (*maze)[ ligne ][ colonne ] = SPACE;
                             ajouter_pile( ligne, colonne, &cStack, &rStack, indexPtr );
                             cont = 4;
                             set = 1;
                             break;
                         }
                     }
                     if ( set == 1 ) {
                         break;
                     }
                 }
             }
             maze_dir[ 0 ] = 0;
             maze_dir[ 1 ] = 0;
             maze_dir[ 2 ] = 0;
             maze_dir[ 3 ] = 0;
         }
             retirer_pile( ligne, colonne, &cStack, &rStack, indexPtr );
             ligne = cStack[ index ];
             colonne = rStack[ index ];
             maze_dir[ 0 ] = 0;
             maze_dir[ 1 ] = 0;
             maze_dir[ 2 ] = 0;
             maze_dir[ 3 ] = 0;
             cont = 4;
     }
 }
References ajouter_pile(), allouerTab1(), allouerTab2(), DIR, retirer_pile(), setValues(), SPACE, and VALUES.
Referenced by creerMaze(), and creerMegaMaze().
mazePlacementComplexe()
void mazePlacementComplexe (int *** maze, int taille, Joueur * j, int posMazeL, int posMazeC)
Definition at line 417 of file generation.c.
{
     if(!(posMazeC%2 || posMazeL%2)){
         // 0 / 0 --> 3 0
         // 2 / 2 --> 2 1
         // 0 / 2 --> 3 2
         // 2 / 0 --> 1 0
         switch (posMazeC+posMazeL) {
             case 0:
                 setCheck(maze,taille,3);
                 setCheck(maze,taille,0);
                 break;
             case 2:
                 if(posMazeL == 2){
                     setCheck(maze,taille,1);
                     setCheck(maze,taille,0);;
                 }else{
                     setCheck(maze,taille,3);
                     setCheck(maze,taille,2);
                 }
                 break;
             case 4:
                 setCheck(maze,taille,2);
                 setCheck(maze,taille,1);
                 break;
         }
     }else{
         if(posMazeL%2 && posMazeC%2){ //no 3
             for(int i=0;i<4;i++){
                 setCheck(maze,taille,i);
             }
         }else{
             if(posMazeC == 2){
             setEnd(maze,taille,2);
             setCheck(maze,taille,1);
             setCheck(maze,taille,3);
             setCheck(maze,taille,2);
             }
             if(posMazeC == 0){
                 setCheck(maze,taille,1);
                 setCheck(maze,taille,3);
                 setCheck(maze,taille,0);
                 setStart(maze,taille,2,j);
             }
             if(posMazeC == 1){
                 if(posMazeL == 2){
                     setCheck(maze,taille,1);
                     setCheck(maze,taille,0);
                     setCheck(maze,taille,2);
                 }else{
                     setCheck(maze,taille,3);
                     setCheck(maze,taille,0);
                     setCheck(maze,taille,2);
                 }
             }
         }
     }
 }
References setCheck(), setEnd(), and setStart().
Referenced by creerMegaMaze().
mazePlacementSimple()
void mazePlacementSimple (int *** maze, int taille, Joueur * j)
Definition at line 367 of file generation.c.
{
     int randPlacement = rand() % 4; // 0 1 2 3
     setEnd(maze,taille,randPlacement);
     setStart(maze,taille,randPlacement,j);
 }
References setEnd(), and setStart().
Referenced by creerMaze().
placerEvents()
placerEvents (Maze * maze, int level)
Permet de placer les events de manières aléatoire dans le labyrythne.
Author
Paul Brechenmacher / Gabin Alquier
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] maze Labyrinthe déja généré avec une taille définie
[in] level Niveau du joueur pour placer plus ou moins d'events
[out] maze Labyrinthe avec des events
Definition at line 513 of file generation.c.
{
     for(int nbEvents = 0; nbEvents < level; nbEvents++){
         int lrandom = rand() % maze->sizeMaze;
         int crandom = rand() % maze->sizeMaze;
         do{
             lrandom = rand() % maze->sizeMaze;
             crandom = rand() % maze->sizeMaze;
         }while(maze->tabMaze[lrandom][crandom] != SPACE);
         maze->tabMaze[lrandom][crandom] = EVENT;
     }
 }
References EVENT, Maze::sizeMaze, SPACE, and Maze::tabMaze.
Referenced by playMazeSimple(), and playMegaMaze().
placerKeys()
void placerKeys (Maze * maze, Joueur * j)
Place les clefs dans les labyrinthes 3x3.
Author
Paul Brechenmacher
Date
(January 8th, 2024 9:29 PM)
Parameters
[in] maze Maze contenant le labyrinthe, son type et sa taille
[in] j Joueur initialisé avec 0 clé trouvée
[out] maze Maze contenant le labyrinthe avec la clé placée
Definition at line 526 of file generation.c.
{
         j->findKeys = 0;
         int lrandom = rand() % maze->sizeMaze;
         int crandom = rand() % maze->sizeMaze;
         do{
             lrandom = rand() % maze->sizeMaze;
             crandom = rand() % maze->sizeMaze;
         }while(maze->tabMaze[lrandom][crandom] != SPACE);
             maze->tabMaze[lrandom][crandom] = KEY;
 }
References Joueur::findKeys, KEY, Maze::sizeMaze, SPACE, and Maze::tabMaze.
Referenced by playMegaMaze().
retirer_pile()
retirer_pile (const int colonne, const int ligne, int ** cStack, int ** rStack, int * index)
Permet de retirer dans la pile une case visitée pour revenir sur des cases disponibles (Randomized depth-first search)
Author
Paul Brechenmacher / Gabin Alquier
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] colonne Colonne actuelle
[in] ligne Ligne actuelle
[in] cStack Pointeur de la pile colonne
[in] rStack Pointeur de la pile ligne
[in] index Pointeur de l'index actuel dans le nombre de cases visitées
[out] rStack Pile colonne modifié ancienne case visitée
[out] cStack Pile colonne modifié ancienne case visitée
Definition at line 286 of file generation.c.
{
     // Retirer la position actuelle de la pile
     (*cStack)[ *index ] = ligne;
     (*rStack)[ *index ] = colonne;
     *index -= 1;
 }
Referenced by mazeGenerator().
setCheck()
void setCheck (int *** maze, int taille, int randPlacement)
Definition at line 375 of file generation.c.
{
     int random = 0;
     random = 1 + rand() % ( taille - 2 );
     // Vérifier que la case choisie est vide (pas un mur)
     // Marquer la case de départ dans la matrice et la retourner
     switch (randPlacement) {
         case 2:
                 while ( (*maze)[ random ][ 1 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ 0 ] = CHECKPOINT;
             break;
         case 3:
             while ( (*maze)[ taille - 2  ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ taille - 1 ][ random ] = CHECKPOINT;
             break;
         case 0:
                 while ( (*maze)[ random ][ taille - 2 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ taille - 1 ] = CHECKPOINT;
             break;
         case 1:
             while ( (*maze)[ 1 ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ 0 ][ random ] = CHECKPOINT;
             break;
         default:
             break;
     }
 }
References CHECKPOINT, and SPACE.
Referenced by mazePlacementComplexe().
setEnd()
setEnd (int *** maze, int taille, int randPlacement)
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] matrice Labyrinthe sans end
[in] taille Jeu contenant l'intégralité des variables du jeu
[in] randPlacement Mode de placement random droite / gauche / haut / pas
[out] maze Labyrinthe avec end
Definition at line 55 of file generation.c.
{
     int random = 0;
     // Choisir une ligne de fin aléatoire dans la dernière colonne
     random = 1 + rand() % ( taille - 2 );
     switch (randPlacement) {
         case 0:
                 while ( (*maze)[ random ][ 1 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ 0 ] = END;
             break;
         case 1:
             while ( (*maze)[ taille - 2  ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ taille - 1 ][ random ] = END;
             break;
         case 2:
                 while ( (*maze)[ random ][ taille - 2 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ taille - 1 ] = END;
             break;
         case 3:
             while ( (*maze)[ 1 ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ 0 ][ random ] = END;
             break;
         default:
             break;
     }
     // Vérifier que la case choisie est vide (pas un mur)
 }
References END, and SPACE.
Referenced by mazePlacementComplexe(), and mazePlacementSimple().
setStart()
setStart (int *** matrice, int taille, int randPlacement, Joueur * j)
Permet de générer le labyrinthe et l'arbre des chemins et placer les entrées et sorties.
Author
Paul Brechenmacher
Date
(January 7th, 2024 9:17 AM)
Parameters
[in] matrice Labyrinthe sans start
[in] taille Jeu contenant l'intégralité des variables du jeu
[in] randPlacement Mode de placement random droite / gauche / haut / pas
[in] j Joueur avec sans positions
[out] j Joueur avec positions placés en positions start
[out] matrice Labyrinthe avec start
Definition at line 5 of file generation.c.
{
     int random = 0;
     random = 1 + rand() % ( taille - 2 );
     // Vérifier que la case choisie est vide (pas un mur)
     // Marquer la case de départ dans la matrice et la retourner
     switch (randPlacement) {
         case 2:
                 while ( (*maze)[ random ][ 1 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ 0 ] = START;
                 j->positions[0] = random;
                 j->positions[1] = 0;
             break;
         case 3:
             while ( (*maze)[ taille - 2  ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ taille - 1 ][ random ] = START;
                 j->positions[0] = taille-1;
                 j->positions[1] = random;
             break;
         case 0:
                 while ( (*maze)[ random ][ taille - 2 ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ random ][ taille - 1 ] = START;
                 j->positions[0] = random;
                 j->positions[1] = taille-1;
             break;
         case 1:
             while ( (*maze)[ 1 ][ random ] != SPACE ) {
                     random = 1 + rand() % ( taille - 2 );
                 }
                 // Marquer la case de fin dans la matrice
                 (*maze)[ 0 ][ random ] = START;
                 j->positions[0] = 0;
                 j->positions[1] = random;
             break;
         default:
             break;
     }
     (*maze)[ j->positions[0] ][ j->positions[1] ] = PLAYER;
 }
References PLAYER, Joueur::positions, SPACE, and START.
Referenced by mazePlacementComplexe(), and mazePlacementSimple().
setValues()
void setValues (int values[4][19], int ligne, int colonne, int taille)
Definition at line 259 of file generation.c.
{
     // Initialiser le tableau de valeurs en fonction de la position actuelle
     int Table[ DIR ][ VALUES ] = {  { ligne, colonne + 1, ligne, colonne + 2, ligne, colonne + 3, ligne - 1, colonne + 1, ligne + 1, colonne + 1, ligne + 1, colonne + 2, ligne - 1, colonne + 2, ligne - 1, colonne + 3, ligne + 1, colonne + 3, colonne < ( taille - 2 ) },
                                  { ligne, colonne - 1, ligne, colonne - 2, ligne, colonne - 3, ligne - 1, colonne - 1, ligne - 1, colonne - 2, ligne - 1, colonne - 3, ligne + 1, colonne - 1, ligne + 1, colonne - 2, ligne + 1, colonne - 3, colonne > 1 },
                                  { ligne - 1, colonne, ligne - 2, colonne, ligne - 3, colonne, ligne - 1, colonne + 1, ligne - 2, colonne + 1, ligne - 3, colonne + 1, ligne - 1, colonne - 1, ligne - 2, colonne - 1, ligne - 3, colonne - 1, ligne > 1 },
                                  { ligne + 1, colonne, ligne + 2, colonne, ligne + 3, colonne, ligne + 1, colonne + 1, ligne + 2, colonne + 1, ligne + 3, colonne + 1, ligne + 1, colonne - 1, ligne + 2, colonne - 1, ligne + 3, colonne - 1, ligne < ( taille - 2 ) } };
     int x, y;
     // Copier les valeurs de Table dans values
     for ( x = 0; x < DIR; ++x ) {
         for ( y = 0; y < VALUES; ++y ) {
             if(Table[ x ][ y ] >= 0 && Table[x][y] < taille){
                 values[ x ][ y ] = Table[ x ][ y ];
             }else{
                 values[ x ][ y ] = 0;
             }
         }
     }
 }
References DIR, and VALUES.
Referenced by mazeGenerator().
verifCheck()
void verifCheck (Jeu * jeu, int ** maze, int positionL, int positionC)
Vérifie si la case demandée est un checkpoint.
Author
Paul Brechenmacher
Date
(January 12th, 2024 5:32 PM)
Parameters
[in] jeu Jeu contenant l'inventaire et les différentes options
[in] maze Tableau 2D représentant le labyrinthe
[in] positionL Position ligne demandée par le joueur
[in] positionC Position colonne demandée par le joueur
Definition at line 557 of file generation.c.
{
     if(positionL > -1 && positionC > -1 && positionC < jeu->maze.sizeMaze && positionL < jeu->maze.sizeMaze){
         if((maze[positionL][positionC]) == CHECKPOINT){
             jeu->j.etatCheckPoint = 0;
             jeu->maze.tabMaze[jeu->j.positions[0]][jeu->j.positions[1]] = SPACE;
             if(positionC == 0){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]-1];
                 jeu->posMaze[1]--;
                 findCheck(jeu,jeu->maze.sizeMaze-1,1);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionL == 0){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]-1][jeu->posMaze[1]];
                 jeu->posMaze[0]--;
                 findCheck(jeu,jeu->maze.sizeMaze-1,0);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionC == (jeu->maze.sizeMaze-1)){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]][jeu->posMaze[1]+1];
                 jeu->posMaze[1]++;
                 afficherMatrice1(jeu->maze.tabMaze,jeu->maze.sizeMaze,jeu->options.typeEmoji,jeu->options.typeMode);
                 findCheck(jeu,0,1);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
             if(positionL == (jeu->maze.sizeMaze-1)){
                 jeu->maze = jeu->megamaze[jeu->posMaze[0]+1][jeu->posMaze[1]];
                 jeu->posMaze[0]++;
                 findCheck(jeu,0,0);
                 jeu->maze.arbreChemin = creerArbreChemins(NULL, jeu->j.positions[0] , jeu->j.positions[1] , jeu->maze.tabMaze,jeu->maze.sizeMaze);
             }
         }
     }
 }
References afficherMatrice1(), Maze::arbreChemin, CHECKPOINT, creerArbreChemins(), Joueur::etatCheckPoint, findCheck(), Jeu::j, Jeu::maze, Jeu::megamaze, Jeu::options, Joueur::positions, Jeu::posMaze, Maze::sizeMaze, SPACE, Maze::tabMaze, Options::typeEmoji, and Options::typeMode.
Referenced by deplacementMaze().