Projet P2 : The Maze: paul.h File Reference
paul.h File Reference
#include "structure.h"
#include <stdio.h>
Macros
#define HAUT 122
#define BAS 115
#define GAUCHE 113
#define DROITE 100
#define HOTBAR1 49
#define HOTBAR2 50
#define HOTBAR3 51
#define HOTBAR4 52
#define HOTBAR5 53
#define ENTER 13
Functions
void emptyBuffer ()
vide le buffer \parameters vide
char deplacementTouche (int etatJoueur)
Permet de capturer une touche utiliser par l'utilisateur et interprète cette entrée en fonction de l'état du joueur fourni et qui renvoie la touche pressée \parameters entier représentant l'etat du joueur (ETAT_ENTER, ETAT_OPTION, ETAT_MENU, ETAT_DRUNK)
void mazeCSV (Maze *maze)
permet d'écrire le contenue de la structure Maze dans un fichier CSV "maze.csv" placé dans le repertoire "out/" \parameters pointeur vers la structure Maze
void mazebigCSV (Maze *megamaze, int i, int j)
megamaze est un labyrinthe de plusieurs labyrinthe et cette fonction permet d'écrire le contenue des différents labyrinthes dans des fichiers CSV "maze<i><j>.csv" placé dans le repertoire "out/megaMazeCSV/" \parameters pointeur vers la structure Maze, entier i, entier j
void afficherMaze (Maze *maze)
affiche le labyrinthe contenue dans la structure Maze dans la console \parameters pointeur vers la structure Maze
Variables
int inversion
Macro Definition Documentation
BAS
#define BAS 115
Definition at line 7 of file paul.h.
DROITE
#define DROITE 100
Definition at line 9 of file paul.h.
ENTER
#define ENTER 13
Definition at line 15 of file paul.h.
GAUCHE
#define GAUCHE 113
Definition at line 8 of file paul.h.
HAUT
#define HAUT 122
Definition at line 6 of file paul.h.
HOTBAR1
#define HOTBAR1 49
Definition at line 10 of file paul.h.
HOTBAR2
#define HOTBAR2 50
Definition at line 11 of file paul.h.
HOTBAR3
#define HOTBAR3 51
Definition at line 12 of file paul.h.
HOTBAR4
#define HOTBAR4 52
Definition at line 13 of file paul.h.
HOTBAR5
#define HOTBAR5 53
Definition at line 14 of file paul.h.
Function Documentation
afficherMaze()
void afficherMaze (Maze * maze)
affiche le labyrinthe contenue dans la structure Maze dans la console \parameters pointeur vers la structure Maze
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Returns
vide
Definition at line 214 of file paul.c.
{
     for (int i = 0; i < maze->sizeMaze; i++) {
         for (int j = 0; j < maze->sizeMaze; j++) {
             printf("%2d ", maze->tabMaze[i][j]);
         }
         printf("\n");
     }
 }
References Maze::sizeMaze, and Maze::tabMaze.
deplacementTouche()
char deplacementTouche (int etatJoueur)
Permet de capturer une touche utiliser par l'utilisateur et interprète cette entrée en fonction de l'état du joueur fourni et qui renvoie la touche pressée \parameters entier représentant l'etat du joueur (ETAT_ENTER, ETAT_OPTION, ETAT_MENU, ETAT_DRUNK)
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Returns
caractère (touche pressée)
Definition at line 18 of file paul.c.
{
   struct termios tty_opts_backup, tty_opts_raw;
   char c;
   int pastermine=1;//par défaut on le met à vrai
   // Back up current TTY settings
   tcgetattr(STDIN_FILENO, &tty_opts_backup);
   // Change TTY settings mode
   cfmakeraw(&tty_opts_raw);
   tcsetattr(STDIN_FILENO, TCSANOW, &tty_opts_raw);
   while (pastermine) {
     c = getchar();
     if (etatJoueur == ETAT_ENTER){
       switch(c){
         case ENTER:
           pastermine =0;
           break;
         default:
           break;
       }
     }
     if (etatJoueur == ETAT_OPTION) {
       switch (c) {
         case HAUT:
           pastermine = 0;
           break;
         case BAS:
           pastermine = 0;
           break;
         case ENTER:
           pastermine = 0;
           break;
         case DROITE:
           pastermine = 0;
           break;
         case GAUCHE:
           pastermine = 0;
           break;
         default:
           break;
       }
     }
     if (etatJoueur == ETAT_MENU) {
       switch (c) {
         case HAUT:
           pastermine = 0;
           break;
         case BAS:
           pastermine = 0;
           break;
         case ENTER:
           pastermine = 0;
           break;
         default:
           break;
       }
     }
     if (etatJoueur == ETAT_DRUNK) {
       switch (c) {
         case HAUT:
           c = BAS;
           pastermine = 0;
           break;
         case GAUCHE:
           c = DROITE;
           pastermine = 0;
           break;
         case DROITE:
           c = GAUCHE;
           pastermine = 0;
           break;
         case BAS:
           c = HAUT;
           pastermine = 0;
           break;
         case HOTBAR1:
           pastermine=0;
           break;
         case HOTBAR2:
           pastermine=0;
           break;
         case HOTBAR3:
           pastermine=0;
           break;
         case HOTBAR4:
           pastermine=0;
           break;
         case HOTBAR5:
           pastermine=0;
           break;
         default:
           break;
       }
     }
     switch(c){
       case HAUT:
         pastermine=0;
         break;
       case GAUCHE:
         pastermine=0;
         break;
       case DROITE:
         pastermine=0;
         break;
       case BAS:
         pastermine=0;
         break;
       case HOTBAR1:
         pastermine=0;
         break;
       case HOTBAR2:
         pastermine=0;
         break;
       case HOTBAR3:
         pastermine=0;
         break;
       case HOTBAR4:
         pastermine=0;
         break;
       case HOTBAR5:
         pastermine=0;
         break;
       case 97:
         printf("\n Vous avez tapé la lettre %c qui permet de quitter le programme!",c);
         /* NE PAS OUBLIER : sinon on ne peut plus écrire dans le terminal */
         // Restore previous TTY settings
         tcsetattr(STDIN_FILENO, TCSANOW, &tty_opts_backup);
         printf("\n");
         exit(0);
       default:
         printf("NON prise en compte\r\n");
         break;
     }
   }
   /* NE PAS OUBLIER : sinon on ne peut plus écrire dans le terminal */
   // Restore previous TTY settings
   tcsetattr(STDIN_FILENO, TCSANOW, &tty_opts_backup);
   return c;
 }
References BAS, DROITE, ENTER, ETAT_DRUNK, ETAT_ENTER, ETAT_MENU, ETAT_OPTION, GAUCHE, HAUT, HOTBAR1, HOTBAR2, HOTBAR3, HOTBAR4, and HOTBAR5.
Referenced by choixMenu(), deplacementMaze(), optionChange(), and regle().
emptyBuffer()
void emptyBuffer ()
vide le buffer \parameters vide
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Returns
vide
Definition at line 13 of file paul.c.
                    {
   char c;
   while (((c = getchar()) != '\n') && (c != EOF));
 }
mazebigCSV()
void mazebigCSV (Maze * maze, int i, int j)
megamaze est un labyrinthe de plusieurs labyrinthe et cette fonction permet d'écrire le contenue des différents labyrinthes dans des fichiers CSV "maze<i><j>.csv" placé dans le repertoire "out/megaMazeCSV/" \parameters pointeur vers la structure Maze, entier i, entier j
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Returns
vide
Definition at line 194 of file paul.c.
{
     char fichiers[40];
     snprintf(fichiers, sizeof(fichiers), "./out/megaMazeCSV/maze%d%d.csv",i,j);
     FILE *fichier = fopen(fichiers, "w");
     if (fichier == NULL) {
         printf("Impossible d'ouvrir le fichier");
     }
     for(int i=0;i<maze->sizeMaze;i++){
       for(int j=0;j<maze->sizeMaze;j++){
         fprintf(fichier,"%d ",maze->tabMaze[i][j]);
       }
       fprintf(fichier, "\n");
     }
     fclose(fichier);
 }
References Maze::sizeMaze, and Maze::tabMaze.
mazeCSV()
void mazeCSV (Maze * maze)
permet d'écrire le contenue de la structure Maze dans un fichier CSV "maze.csv" placé dans le repertoire "out/" \parameters pointeur vers la structure Maze
Author
Paul Le Blanc
Date
(January 9th, 2024 5:00 PM)
Returns
vide
Definition at line 177 of file paul.c.
{
     FILE *fichier = fopen("out/maze.csv", "w");
     if (fichier == NULL) {
         printf("Impossible d'ouvrir le fichier");
     }
     for(int i=0;i<(maze->sizeMaze);i++){
       for(int j=0;j<(maze->sizeMaze);j++){
         fprintf(fichier,"%d ",maze->tabMaze[i][j]);
       }
       fprintf(fichier, "\n");
     }
     fclose(fichier);
 }
References Maze::sizeMaze, and Maze::tabMaze.
Variable Documentation
inversion
int inversion extern
Definition at line 11 of file paul.c.